# Generated by Django 2.1.5 on 2020-01-05 20:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userexecutesql',
            name='id_datalist',
            field=models.ForeignKey(blank=True, db_column='id_datalist', null=True, on_delete=django.db.models.deletion.PROTECT, to='database.DataList', verbose_name='데이터리스트'),
        ),
    ]
