# Generated by Django 2.1.5 on 2020-01-06 09:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('database', '0002_userexecutesql_id_datalist'),
    ]

    operations = [
        migrations.CreateModel(
            name='TuningList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=100, null=True, verbose_name='제목')),
                ('sql_id', models.CharField(blank=True, max_length=100, null=True, verbose_name='SQL_ID')),
                ('sql_type', models.CharField(choices=[('0', '신규'), ('1', '변경')], default='0', max_length=30, verbose_name='신규or변경')),
                ('sql_info', models.TextField(blank=True, max_length=10000, null=True, verbose_name='SQL정보')),
                ('tuning_info', models.TextField(blank=True, max_length=10000, null=True, verbose_name='튜너의견')),
                ('asis_sql_text', models.TextField(blank=True, max_length=10000, null=True, verbose_name='튜닝전SQL')),
                ('asis_elapsed_time', models.FloatField(default=0, verbose_name='튜닝 전 수행시간')),
                ('tobe_sql_text', models.TextField(blank=True, max_length=10000, null=True, verbose_name='튜닝후SQL')),
                ('tobe_elapsed_time', models.FloatField(default=0, verbose_name='튜닝 후 수행시간')),
                ('tuning_dtm', models.DateTimeField(blank=True, null=True, verbose_name='튜닝일자')),
                ('dist_dtm', models.DateTimeField(blank=True, null=True, verbose_name='배포일자')),
                ('reg_dtm', models.DateTimeField(auto_now_add=True, verbose_name='등록일자')),
                ('mod_dtm', models.DateTimeField(auto_now=True, verbose_name='수정일자')),
                ('id_dblist', models.ForeignKey(blank=True, db_column='id_dblist', null=True, on_delete=django.db.models.deletion.PROTECT, to='database.DbList', verbose_name='DB명')),
                ('id_domain', models.ForeignKey(blank=True, db_column='id_domain', null=True, on_delete=django.db.models.deletion.PROTECT, to='database.Domain', verbose_name='업무도메인명')),
                ('id_mod_user', models.ForeignKey(blank=True, db_column='id_mod_user', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='User_TuningList_mod_user', to=settings.AUTH_USER_MODEL, verbose_name='수정자')),
                ('id_reg_user', models.ForeignKey(blank=True, db_column='id_reg_user', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='User_TuningList_reg_user', to=settings.AUTH_USER_MODEL, verbose_name='등록자')),
                ('id_tuning_user', models.ForeignKey(blank=True, db_column='id_tuning_user', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='User_TuningList_tuning_user', to=settings.AUTH_USER_MODEL, verbose_name='등록자')),
            ],
            options={
                'verbose_name': '튜닝요청',
                'verbose_name_plural': '튜닝요청',
                'db_table': 'cust_tuning_list',
            },
        ),
        migrations.CreateModel(
            name='TuningStatus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(max_length=100, verbose_name='튜닝진행상태')),
                ('reg_dtm', models.DateTimeField(auto_now_add=True, verbose_name='등록일자')),
                ('mod_dtm', models.DateTimeField(auto_now=True, verbose_name='수정일자')),
                ('id_mod_user', models.ForeignKey(blank=True, db_column='id_mod_user', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='User_TuningStatus_mod_user', to=settings.AUTH_USER_MODEL, verbose_name='수정자')),
                ('id_reg_user', models.ForeignKey(blank=True, db_column='id_reg_user', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='User_TuningStatus_reg_user', to=settings.AUTH_USER_MODEL, verbose_name='등록자')),
            ],
            options={
                'verbose_name': '튜닝진행상태 (튜닝요청/튜닝완료/배포요청 등)',
                'verbose_name_plural': '튜닝진행상태 (튜닝요청/튜닝완료/배포요청 등)',
                'db_table': 'cust_tuning_status',
            },
        ),
        migrations.AddField(
            model_name='tuninglist',
            name='id_tuningstatus',
            field=models.ForeignKey(blank=True, db_column='id_tuningstatus', null=True, on_delete=django.db.models.deletion.PROTECT, to='database.TuningStatus', verbose_name='튜닝진행상태'),
        ),
    ]
