# Generated by Django 2.1.5 on 2020-01-06 11:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0003_auto_20200106_0946'),
    ]

    operations = [
        migrations.AddField(
            model_name='tuninglist',
            name='id_datalist',
            field=models.ForeignKey(blank=True, db_column='id_datalist', null=True, on_delete=django.db.models.deletion.PROTECT, to='database.DataList', verbose_name='DataList'),
        ),
        migrations.AlterField(
            model_name='tuninglist',
            name='sql_type',
            field=models.CharField(choices=[('0', '운영업무-신규'), ('1', '운영업부-변경'), ('2', '정보성업무/분석')], default='0', max_length=30, verbose_name='신규or변경'),
        ),
    ]
