# Generated by Django 2.1.5 on 2020-01-06 12:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0004_auto_20200106_1102'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='datalist',
            name='id_tablelist',
        ),
        migrations.AddField(
            model_name='datalist',
            name='id_dblist',
            field=models.ForeignKey(blank=True, db_column='id_dblist', null=True, on_delete=django.db.models.deletion.PROTECT, to='database.DbList', verbose_name='DB명'),
        ),
    ]
