# Generated by Django 2.1.5 on 2020-01-06 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0005_auto_20200106_1255'),
    ]

    operations = [
        migrations.AddField(
            model_name='domain',
            name='exp_order',
            field=models.IntegerField(blank=True, default=100, null=True, verbose_name='화면노출순서(0이면 노출 안됨)'),
        ),
        migrations.AlterField(
            model_name='channel',
            name='exp_order',
            field=models.IntegerField(blank=True, default=100, null=True, verbose_name='화면노출순서(0이면 노출 안됨)'),
        ),
    ]
