# Generated by Django 2.1.5 on 2020-01-06 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0006_auto_20200106_1305'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datalist',
            name='exp_order',
            field=models.IntegerField(blank=True, default=99, null=True, verbose_name='화면노출순서'),
        ),
        migrations.AlterField(
            model_name='tuninglist',
            name='asis_elapsed_time',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='튜닝 전 수행 시간'),
        ),
        migrations.AlterField(
            model_name='tuninglist',
            name='tobe_elapsed_time',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='튜닝 후 수행 시간'),
        ),
    ]
