# Generated by Django 2.1.5 on 2020-01-06 16:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0008_auto_20200106_1611'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tuninglist',
            name='id_datalist',
            field=models.ForeignKey(blank=True, db_column='id_datalist', null=True, on_delete=django.db.models.deletion.CASCADE, to='database.DataList', verbose_name='DataList'),
        ),
    ]
