# Generated by Django 2.1.5 on 2020-01-07 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0009_auto_20200106_1612'),
    ]

    operations = [
        migrations.CreateModel(
            name='abc',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=100, null=True, verbose_name='제목')),
                ('sql_id', models.CharField(blank=True, max_length=100, null=True, verbose_name='SQL_ID')),
            ],
            options={
                'verbose_name': '테슽',
                'verbose_name_plural': '테슽',
                'db_table': 'abc',
            },
        ),
    ]
