# Generated by Django 2.1.5 on 2020-01-07 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0010_abc'),
    ]

    operations = [
        migrations.AddField(
            model_name='abc',
            name='aa',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='SQL_ID'),
        ),
    ]
