# Generated by Django 2.1.5 on 2020-01-07 12:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0011_abc_aa'),
    ]

    operations = [
        migrations.DeleteModel(
            name='abc',
        ),
    ]
