# Generated by Django 2.1.5 on 2020-01-07 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0012_delete_abc'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserVisit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, null=True, verbose_name='이름')),
                ('sabun', models.CharField(blank=True, max_length=100, null=True, verbose_name='사번')),
                ('team_name', models.CharField(blank=True, max_length=100, null=True, verbose_name='팀명')),
                ('menu_cd', models.CharField(blank=True, max_length=100, null=True, verbose_name='사번')),
                ('reg_dtm', models.DateTimeField(auto_now_add=True, verbose_name='일자')),
            ],
            options={
                'verbose_name': '사용자방문이력',
                'verbose_name_plural': '사용자방문이력',
                'db_table': 'cust_user_visit',
            },
        ),
    ]
