# Generated by Django 2.1.5 on 2020-01-07 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0013_uservisit'),
    ]

    operations = [
        migrations.CreateModel(
            name='MenuList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('menu_name', models.CharField(blank=True, max_length=100, null=True, verbose_name='메뉴명')),
                ('menu_explain', models.CharField(blank=True, max_length=100, null=True, verbose_name='비고')),
                ('reg_dtm', models.DateTimeField(auto_now_add=True, verbose_name='일자')),
            ],
            options={
                'verbose_name': '메뉴분류',
                'verbose_name_plural': '메뉴분류',
                'db_table': 'cust_menu_list',
            },
        ),
    ]
