# Generated by Django 2.1.5 on 2020-01-07 16:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0015_auto_20200107_1557'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='uservisit',
            name='menu_cd',
        ),
        migrations.AddField(
            model_name='uservisit',
            name='id_menulist',
            field=models.ForeignKey(blank=True, db_column='id_menulist', null=True, on_delete=django.db.models.deletion.PROTECT, to='database.MenuList', verbose_name='메뉴리스트'),
        ),
    ]
