# Generated by Django 2.1.5 on 2020-01-08 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0016_auto_20200107_1606'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='batchlist',
            options={'verbose_name': '9-3.SmartDBA배치', 'verbose_name_plural': '9-3.SmartDBA배치'},
        ),
        migrations.AlterModelOptions(
            name='menulist',
            options={'verbose_name': '8-1.메뉴분류', 'verbose_name_plural': '8-1.메뉴분류'},
        ),
        migrations.AlterModelOptions(
            name='tuninglist',
            options={'verbose_name': '9-2.튜닝요청', 'verbose_name_plural': '9-2.튜닝요청'},
        ),
        migrations.AlterModelOptions(
            name='tuningstatus',
            options={'verbose_name': '8-2.튜닝진행상태 (튜닝요청/튜닝완료/배포요청 등)', 'verbose_name_plural': '8-2.튜닝진행상태 (튜닝요청/튜닝완료/배포요청 등)'},
        ),
        migrations.AlterModelOptions(
            name='userclickdata',
            options={'verbose_name': '9-5.사용자 클릭데이터', 'verbose_name_plural': '9-5.사용자 클릭데이터'},
        ),
        migrations.AlterModelOptions(
            name='userexecutesql',
            options={'verbose_name': '9-5.사용자 실행SQL', 'verbose_name_plural': '9-5.사용자 실행SQL'},
        ),
        migrations.AlterModelOptions(
            name='userrequestdata',
            options={'verbose_name': '9-3.사용자 데이터 요청', 'verbose_name_plural': '9-3.사용자 데이터 요청'},
        ),
        migrations.AlterModelOptions(
            name='userrequestword',
            options={'verbose_name': '9-4.사용자 데이터 요청', 'verbose_name_plural': '9-4.사용자 데이터 요청'},
        ),
        migrations.AlterModelOptions(
            name='usersearchkeyword',
            options={'verbose_name': '9-6.사용자 검색키워드', 'verbose_name_plural': '9-6.사용자 검색키워드'},
        ),
        migrations.AlterModelOptions(
            name='uservisit',
            options={'verbose_name': '9-1.사용자방문이력', 'verbose_name_plural': '9-1.사용자방문이력'},
        ),
        migrations.AddField(
            model_name='userrequestdata',
            name='complete_yn',
            field=models.CharField(blank=True, choices=[('1', 'Y'), ('0', 'N')], default='0', max_length=30, null=True, verbose_name='완료여부'),
        ),
        migrations.AddField(
            model_name='userrequestword',
            name='complete_yn',
            field=models.CharField(blank=True, choices=[('1', 'Y'), ('0', 'N')], default='0', max_length=30, null=True, verbose_name='완료여부'),
        ),
    ]
