# Generated by Django 2.1.5 on 2020-01-09 18:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0017_auto_20200108_0855'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userexecutesql',
            name='id_datalist',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='데이터리스트'),
        ),
        migrations.AlterField(
            model_name='userexecutesql',
            name='id_reg_user',
            field=models.ForeignKey(blank=True, db_column='id_reg_user', null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='등록자'),
        ),
    ]
