# Generated by Django 2.1.5 on 2020-01-11 19:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0020_auto_20200111_1930'),
    ]

    operations = [
        migrations.CreateModel(
            name='DatabaseMap',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('xy', models.CharField(blank=True, max_length=100, null=True, verbose_name='좌표')),
                ('map_type', models.CharField(blank=True, choices=[('0', '도메인레벨'), ('1', 'DB레벨')], max_length=100, null=True, verbose_name='구분')),
                ('id_dblist', models.ForeignKey(blank=True, db_column='id_dblist', null=True, on_delete=django.db.models.deletion.PROTECT, to='database.DbList', verbose_name='DB명')),
                ('id_domain', models.ForeignKey(blank=True, db_column='id_domain', null=True, on_delete=django.db.models.deletion.PROTECT, to='database.Domain', verbose_name='업무도메인명')),
            ],
            options={
                'verbose_name': '데이터베이스 이미지 매핑 테이블',
                'verbose_name_plural': '데이터베이스 이미지 매핑 테이블',
                'db_table': 'cust_database_map',
            },
        ),
    ]
