# Generated by Django 2.1.5 on 2020-01-11 20:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0021_databasemap'),
    ]

    operations = [
        migrations.AddField(
            model_name='databasemap',
            name='etc1',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='기타'),
        ),
    ]
