# Generated by Django 2.1.5 on 2020-01-16 16:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0022_databasemap_etc1'),
    ]

    operations = [
        migrations.CreateModel(
            name='TableListDataHubDHUBOWN',
            fields=[
            ],
            options={
                'verbose_name': '데이터허브DHUB_OWN',
                'verbose_name_plural': '데이터허브DHUB_OWN',
                'proxy': True,
                'indexes': [],
            },
            bases=('database.tablelist',),
        ),
    ]
