# Generated by Django 2.1.5 on 2020-01-18 03:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('database', '0024_datalist_id_req_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='datalist',
            name='id_prov_user1',
            field=models.ForeignKey(blank=True, db_column='id_prov_user1', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='User_DataList_prov_user1', to=settings.AUTH_USER_MODEL, verbose_name='1차 승인'),
        ),
        migrations.AddField(
            model_name='datalist',
            name='id_prov_user2',
            field=models.ForeignKey(blank=True, db_column='id_prov_user2', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='User_DataList_prov_user2', to=settings.AUTH_USER_MODEL, verbose_name='2차 승인'),
        ),
        migrations.AddField(
            model_name='datalist',
            name='prov_yn1',
            field=models.CharField(blank=True, choices=[('1', 'Y'), ('0', 'N')], default='0', max_length=100, null=True, verbose_name='1차승인여부(보안)'),
        ),
        migrations.AddField(
            model_name='datalist',
            name='prov_yn2',
            field=models.CharField(blank=True, choices=[('1', 'Y'), ('0', 'N')], default='0', max_length=100, null=True, verbose_name='2차승인여부(성능)'),
        ),
    ]
