# Generated by Django 2.1.5 on 2020-01-18 04:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0025_auto_20200118_0358'),
    ]

    operations = [
        migrations.AddField(
            model_name='datalist',
            name='privacy_yn',
            field=models.CharField(blank=True, choices=[('1', 'Y'), ('0', 'N')], default='0', max_length=100, null=True, verbose_name='개인정보유무'),
        ),
    ]
