# Generated by Django 2.1.5 on 2020-01-21 17:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0027_secureapprove'),
    ]

    operations = [
        migrations.CreateModel(
            name='RegisterData',
            fields=[
            ],
            options={
                'verbose_name': '[DataList] DevOps-데이터 생성',
                'verbose_name_plural': '[DataList] DevOps-데이터 생성',
                'proxy': True,
                'indexes': [],
            },
            bases=('database.datalist',),
        ),
        migrations.AlterModelOptions(
            name='datalist',
            options={'verbose_name': '3-1.데이터 리스트', 'verbose_name_plural': '3-1.데이터 리스트'},
        ),
        migrations.AlterModelOptions(
            name='secureapprove',
            options={'verbose_name': '[DataList] 보안센터-데이터노출승인', 'verbose_name_plural': '[DataList] 보안센터-데이터노출승인'},
        ),
    ]
