# Generated by Django 2.1.5 on 2020-01-21 21:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0028_auto_20200121_1753'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='batchlist',
            options={'verbose_name': '[DBA-09] SmartDBA배치', 'verbose_name_plural': '[DBA-09] SmartDBA배치'},
        ),
        migrations.AlterModelOptions(
            name='channel',
            options={'verbose_name': '[DBA-02] 채널구분 (기간계/정보계/MCPC)', 'verbose_name_plural': '[DBA-02] 채널구분 (기간계/정보계/MCPC)'},
        ),
        migrations.AlterModelOptions(
            name='columnlist',
            options={'verbose_name': '[DBA-07] Column 리스트', 'verbose_name_plural': '[DBA-07] Column 리스트'},
        ),
        migrations.AlterModelOptions(
            name='databasemap',
            options={'verbose_name': '[DBA-10] 데이터베이스 지도 이미지 매핑 테이블', 'verbose_name_plural': '[DBA-10] 데이터베이스 지도 이미지 매핑 테이블'},
        ),
        migrations.AlterModelOptions(
            name='datalist',
            options={'verbose_name': '[DBA-08] 데이터 리스트', 'verbose_name_plural': '[DBA-08] 데이터 리스트'},
        ),
        migrations.AlterModelOptions(
            name='datatype',
            options={'verbose_name': '[DBA-03] 데이터유형구분 (real/staging...)', 'verbose_name_plural': '[DBA-03] 데이터유형구분 (real/staging...)'},
        ),
        migrations.AlterModelOptions(
            name='dbdetail',
            options={'verbose_name': '[DBA-05] Database 하위 레벨 리스트', 'verbose_name_plural': '[DBA-05] Database 하위 레벨 리스트'},
        ),
        migrations.AlterModelOptions(
            name='dblist',
            options={'verbose_name': '[DBA-04] Database 상위 레벨 리스트', 'verbose_name_plural': '[DBA-04] Database 상위 레벨 리스트'},
        ),
        migrations.AlterModelOptions(
            name='domain',
            options={'verbose_name': '[DBA-01] 도메인구분 (고객/상품/주문....)', 'verbose_name_plural': '[DBA-01] 도메인구분 (고객/상품/주문....)'},
        ),
        migrations.AlterModelOptions(
            name='menulist',
            options={'verbose_name': '99.메뉴분류', 'verbose_name_plural': '99.메뉴분류'},
        ),
        migrations.AlterModelOptions(
            name='processlist',
            options={'verbose_name': '99.고객 행동 프로세스 (앱실행/주문완료...)', 'verbose_name_plural': '99.고객 행동 프로세스 (앱실행/주문완료...)'},
        ),
        migrations.AlterModelOptions(
            name='tablelist',
            options={'verbose_name': '[DBA-06] Table 리스트', 'verbose_name_plural': '[DBA-06] Table 리스트'},
        ),
        migrations.AlterModelOptions(
            name='tuninglist',
            options={'verbose_name': '[DBA-12] 튜닝요청', 'verbose_name_plural': '[DBA-12] 튜닝요청'},
        ),
        migrations.AlterModelOptions(
            name='tuningstatus',
            options={'verbose_name': '[DBA-11] 튜닝진행상태 (튜닝요청/튜닝완료/배포요청 등)', 'verbose_name_plural': '[DBA-11] 튜닝진행상태 (튜닝요청/튜닝완료/배포요청 등)'},
        ),
        migrations.AlterModelOptions(
            name='userclickdata',
            options={'verbose_name': '99.사용자 클릭데이터', 'verbose_name_plural': '99.사용자 클릭데이터'},
        ),
        migrations.AlterModelOptions(
            name='userexecutesql',
            options={'verbose_name': '99.사용자 실행SQL', 'verbose_name_plural': '99.사용자 실행SQL'},
        ),
        migrations.AlterModelOptions(
            name='userrequestdata',
            options={'verbose_name': '99.사용자 데이터 요청', 'verbose_name_plural': '99.사용자 데이터 요청'},
        ),
        migrations.AlterModelOptions(
            name='userrequestword',
            options={'verbose_name': '99.사용자 데이터 요청', 'verbose_name_plural': '99.사용자 데이터 요청'},
        ),
        migrations.AlterModelOptions(
            name='usersearchkeyword',
            options={'verbose_name': '99.사용자 검색키워드', 'verbose_name_plural': '99.사용자 검색키워드'},
        ),
        migrations.AlterModelOptions(
            name='uservisit',
            options={'verbose_name': '99.사용자방문이력', 'verbose_name_plural': '99.사용자방문이력'},
        ),
        migrations.RemoveField(
            model_name='datalist',
            name='id_processlist',
        ),
        migrations.RemoveField(
            model_name='datalist',
            name='id_tablelist_member_table',
        ),
        migrations.AlterField(
            model_name='datalist',
            name='id_prov_user1',
            field=models.ForeignKey(blank=True, db_column='id_prov_user1', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='User_DataList_prov_user1', to=settings.AUTH_USER_MODEL, verbose_name='1차 승인(보안)'),
        ),
        migrations.AlterField(
            model_name='datalist',
            name='id_prov_user2',
            field=models.ForeignKey(blank=True, db_column='id_prov_user2', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='User_DataList_prov_user2', to=settings.AUTH_USER_MODEL, verbose_name='2차 승인(성능)'),
        ),
    ]
