# Generated by Django 2.1.5 on 2020-01-21 23:16

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('database', '0029_auto_20200121_2150'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='menulist',
            options={'verbose_name': '[z99] 메뉴분류', 'verbose_name_plural': '[z99] 메뉴분류'},
        ),
        migrations.AlterModelOptions(
            name='processlist',
            options={'verbose_name': '[z99] 고객 행동 프로세스 (앱실행/주문완료...)', 'verbose_name_plural': '[z99] 고객 행동 프로세스 (앱실행/주문완료...)'},
        ),
        migrations.AlterModelOptions(
            name='tablelistdatahubdhubown',
            options={'verbose_name': '[z99] 데이터허브DHUB_OWN', 'verbose_name_plural': '[z99] 데이터허브DHUB_OWN'},
        ),
        migrations.AlterModelOptions(
            name='tuninglist',
            options={'verbose_name': '[DBA-11] 튜닝요청', 'verbose_name_plural': '[DBA-11] 튜닝요청'},
        ),
        migrations.AlterModelOptions(
            name='tuningstatus',
            options={'verbose_name': '[DBA-10] 튜닝진행상태 (튜닝요청/튜닝완료/배포요청 등)', 'verbose_name_plural': '[DBA-10] 튜닝진행상태 (튜닝요청/튜닝완료/배포요청 등)'},
        ),
        migrations.AlterModelOptions(
            name='userclickdata',
            options={'verbose_name': '[z99] 사용자 클릭데이터', 'verbose_name_plural': '[z99] 사용자 클릭데이터'},
        ),
        migrations.AlterModelOptions(
            name='userexecutesql',
            options={'verbose_name': '[z99] 사용자 실행SQL', 'verbose_name_plural': '[z99] 사용자 실행SQL'},
        ),
        migrations.AlterModelOptions(
            name='userrequestdata',
            options={'verbose_name': '[z99] 사용자 데이터 요청', 'verbose_name_plural': '[z99] 사용자 데이터 요청'},
        ),
        migrations.AlterModelOptions(
            name='userrequestword',
            options={'verbose_name': '[z99] 사용자 데이터 요청', 'verbose_name_plural': '[z99] 사용자 데이터 요청'},
        ),
        migrations.AlterModelOptions(
            name='usersearchkeyword',
            options={'verbose_name': '[z99] 사용자 검색키워드', 'verbose_name_plural': '[z99] 사용자 검색키워드'},
        ),
        migrations.AlterModelOptions(
            name='uservisit',
            options={'verbose_name': '[z99] 사용자방문이력', 'verbose_name_plural': '[z99] 사용자방문이력'},
        ),
        migrations.AddField(
            model_name='domain',
            name='it_manager',
            field=models.ManyToManyField(blank=True, db_table='cust_domain_it_manager', max_length=300, to=settings.AUTH_USER_MODEL, verbose_name='IT담당자'),
        ),
    ]
