# Generated by Django 2.1.5 on 2020-01-21 23:30

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('database', '0030_auto_20200121_2316'),
    ]

    operations = [
        migrations.AddField(
            model_name='domain',
            name='dev_manager',
            field=models.ManyToManyField(blank=True, db_table='cust_domain_dev_manager', max_length=300, related_name='domain_dev_manager', to=settings.AUTH_USER_MODEL, verbose_name='개발 담당자'),
        ),
        migrations.AlterField(
            model_name='domain',
            name='it_manager',
            field=models.ManyToManyField(blank=True, db_table='cust_domain_it_manager', max_length=300, related_name='domain_it_manager', to=settings.AUTH_USER_MODEL, verbose_name='GSSHOP 담당자'),
        ),
    ]
