# Generated by Django 2.1.5 on 2020-01-22 07:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0032_domainanddblist'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='domainanddblist',
            name='id_dblist',
        ),
        migrations.RemoveField(
            model_name='domainanddblist',
            name='id_domain',
        ),
        migrations.RemoveField(
            model_name='domainanddblist',
            name='id_mod_user',
        ),
        migrations.RemoveField(
            model_name='domainanddblist',
            name='id_reg_user',
        ),
        migrations.DeleteModel(
            name='DomainAndDbList',
        ),
    ]
