# Generated by Django 2.1.5 on 2020-01-22 08:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0034_domainanddblist'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='dblist',
            options={'ordering': ['db_use'], 'verbose_name': '[DBA-04] Database 상위 레벨 리스트', 'verbose_name_plural': '[DBA-04] Database 상위 레벨 리스트'},
        ),
    ]
