# Generated by Django 2.1.5 on 2020-01-22 08:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0035_auto_20200122_0807'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='domain',
            name='dev_manager',
        ),
        migrations.RemoveField(
            model_name='domain',
            name='it_manager',
        ),
    ]
