# Generated by Django 2.1.5 on 2020-01-22 08:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('database', '0037_auto_20200122_0815'),
    ]

    operations = [
        migrations.CreateModel(
            name='MenuPermission',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reg_dtm', models.DateTimeField(auto_now_add=True, verbose_name='일자')),
                ('mod_dtm', models.DateTimeField(auto_now=True, verbose_name='수정일자')),
                ('id_grantee_user', models.ForeignKey(blank=True, db_column='id_grantee_user', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='User_MenuPermission_grantee_user', to=settings.AUTH_USER_MODEL, verbose_name='GRANTEE')),
                ('id_menulist', models.ForeignKey(blank=True, db_column='id_menulist', null=True, on_delete=django.db.models.deletion.PROTECT, to='database.MenuList', verbose_name='메뉴명')),
                ('id_mod_user', models.ForeignKey(blank=True, db_column='id_mod_user', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='User_MenuPermission_mod_user', to=settings.AUTH_USER_MODEL, verbose_name='수정자')),
                ('id_reg_user', models.ForeignKey(blank=True, db_column='id_reg_user', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='User_MenuPermission_reg_user', to=settings.AUTH_USER_MODEL, verbose_name='등록자')),
            ],
            options={
                'verbose_name': '[z99] 메뉴사용자권한',
                'verbose_name_plural': '[z99] 메뉴사용자권한',
                'db_table': 'cust_menu_permission',
            },
        ),
    ]
