# Generated by Django 2.1.5 on 2020-01-25 16:18

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('database', '0039_menulist_default_permission_yn'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='datalist',
            name='id_req_user',
        ),
        migrations.AddField(
            model_name='datalist',
            name='execute_cnt',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='수행횟수'),
        ),
        migrations.AddField(
            model_name='datalist',
            name='it_mod_psbl_users',
            field=models.ManyToManyField(blank=True, db_table='cust_datalist_user_it_mod_psbl_users', max_length=300, related_name='cust_datalist_user_it_mod_psbl_users', to=settings.AUTH_USER_MODEL, verbose_name='수정가능한직원들'),
        ),
        migrations.AddField(
            model_name='datalist',
            name='it_req_users',
            field=models.ManyToManyField(blank=True, db_table='cust_datalist_user_it_req_users', max_length=300, related_name='cust_datalist_user_it_req_users', to=settings.AUTH_USER_MODEL, verbose_name='요청자들'),
        ),
    ]
