# Generated by Django 2.1.5 on 2020-01-25 16:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0040_auto_20200125_1618'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='datalist',
            name='it_mod_psbl_users',
        ),
        migrations.RemoveField(
            model_name='datalist',
            name='it_req_users',
        ),
    ]
