# Generated by Django 2.1.5 on 2020-01-25 16:22

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('database', '0041_auto_20200125_1621'),
    ]

    operations = [
        migrations.AddField(
            model_name='datalist',
            name='id_mod_psbl_users',
            field=models.ManyToManyField(blank=True, db_table='cust_datalist_user_id_mod_psbl_users', max_length=300, related_name='cust_datalist_user_id_mod_psbl_users', to=settings.AUTH_USER_MODEL, verbose_name='수정가능한직원들'),
        ),
        migrations.AddField(
            model_name='datalist',
            name='id_req_users',
            field=models.ManyToManyField(blank=True, db_table='cust_datalist_user_id_req_users', max_length=300, related_name='cust_datalist_user_id_req_users', to=settings.AUTH_USER_MODEL, verbose_name='요청자들'),
        ),
    ]
