# Generated by Django 2.1.5 on 2020-01-26 00:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0043_datalist_realoretl'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datalist',
            name='prov_yn1',
            field=models.CharField(blank=True, choices=[('1', 'Y'), ('0', 'N')], default='0', max_length=100, null=True, verbose_name='보안 승인여부'),
        ),
        migrations.AlterField(
            model_name='datalist',
            name='prov_yn2',
            field=models.CharField(blank=True, choices=[('1', 'Y'), ('0', 'N')], default='0', max_length=100, null=True, verbose_name='성능 승인여부'),
        ),
        migrations.AlterField(
            model_name='datalist',
            name='sql_text',
            field=models.TextField(blank=True, help_text=' <font color=red><b>":"로 바인딩하여 SQL을 작성하면 동적으로 파라메터 값을 받을 수 있습니다.</b></font><br>예를들면, :상픔코드, :주문일자 와 같이 바인딩 사용 시 사용자가 SQL을 실행할 때 상품코드와 주문일자를 입력할 수 있습니다.', max_length=10000, null=True, verbose_name='관련SQL'),
        ),
        migrations.AlterField(
            model_name='tuninglist',
            name='id_tuning_user',
            field=models.ForeignKey(blank=True, db_column='id_tuning_user', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='User_TuningList_tuning_user', to=settings.AUTH_USER_MODEL, verbose_name='튜너'),
        ),
    ]
