# Generated by Django 2.1.5 on 2020-01-26 23:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0046_auto_20200126_2332'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tuninglist',
            name='sql_id',
            field=models.CharField(default='title', max_length=100, verbose_name='SQL_ID'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='tuninglist',
            name='title',
            field=models.CharField(default='title', max_length=100, verbose_name='제목'),
            preserve_default=False,
        ),
    ]
