# Generated by Django 2.1.5 on 2020-01-26 23:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0049_auto_20200126_2340'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tuninglist',
            name='asis_elapsed_time',
            field=models.CharField(max_length=100, null=True, verbose_name='튜닝 전 수행 시간'),
        ),
        migrations.AlterField(
            model_name='tuninglist',
            name='asis_sql_text',
            field=models.TextField(max_length=10000, null=True, verbose_name='튜닝전SQL'),
        ),
        migrations.AlterField(
            model_name='tuninglist',
            name='dist_dtm',
            field=models.DateTimeField(null=True, verbose_name='배포일자'),
        ),
        migrations.AlterField(
            model_name='tuninglist',
            name='id_dblist',
            field=models.ForeignKey(db_column='id_dblist', null=True, on_delete=django.db.models.deletion.PROTECT, to='database.DbList', verbose_name='DB명'),
        ),
        migrations.AlterField(
            model_name='tuninglist',
            name='id_tuningstatus',
            field=models.ForeignKey(db_column='id_tuningstatus', default=0, null=True, on_delete=django.db.models.deletion.PROTECT, to='database.TuningStatus', verbose_name='튜닝진행상태'),
        ),
        migrations.AlterField(
            model_name='tuninglist',
            name='sql_info',
            field=models.TextField(max_length=10000, null=True, verbose_name='SQL정보'),
        ),
        migrations.AlterField(
            model_name='tuninglist',
            name='title',
            field=models.CharField(max_length=100, null=True, verbose_name='제목'),
        ),
    ]
