# Generated by Django 2.1.5 on 2020-01-26 23:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0050_auto_20200126_2347'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tuninglist',
            name='id_tuningstatus',
            field=models.ForeignKey(db_column='id_tuningstatus', default=1, null=True, on_delete=django.db.models.deletion.PROTECT, to='database.TuningStatus', verbose_name='튜닝진행상태'),
        ),
    ]
