# Generated by Django 2.1.5 on 2020-01-26 23:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0053_auto_20200126_2352'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tuninglist',
            name='id_dblist',
            field=models.ForeignKey(db_column='id_dblist', default=10, null=True, on_delete=django.db.models.deletion.PROTECT, to='database.DbList', verbose_name='DB명'),
        ),
    ]
