# Generated by Django 2.1.5 on 2020-01-26 23:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0054_auto_20200126_2353'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tuninglist',
            name='id_domain',
            field=models.ForeignKey(db_column='id_domain', null=True, on_delete=django.db.models.deletion.PROTECT, to='database.Domain', verbose_name='업무도메인명'),
        ),
    ]
