# Generated by Django 2.1.5 on 2020-01-27 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0055_auto_20200126_2354'),
    ]

    operations = [
        migrations.AddField(
            model_name='tuninglist',
            name='avg_rows',
            field=models.IntegerField(null=True, verbose_name='평균 결과 건수'),
        ),
        migrations.AddField(
            model_name='tuninglist',
            name='bind_value',
            field=models.TextField(blank=True, max_length=500, null=True, verbose_name='바인딩값'),
        ),
        migrations.AddField(
            model_name='tuninglist',
            name='expect_sql_text',
            field=models.IntegerField(null=True, verbose_name='기대 수행 시간'),
        ),
        migrations.AlterField(
            model_name='tuninglist',
            name='asis_elapsed_time',
            field=models.IntegerField(null=True, verbose_name='튜닝 전 수행 시간'),
        ),
        migrations.AlterField(
            model_name='tuninglist',
            name='sql_info',
            field=models.TextField(max_length=10000, null=True, verbose_name='SQL 설명'),
        ),
        migrations.AlterField(
            model_name='tuninglist',
            name='tobe_elapsed_time',
            field=models.IntegerField(blank=True, null=True, verbose_name='튜닝 후 수행 시간'),
        ),
    ]
