# Generated by Django 2.1.5 on 2020-01-27 12:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0056_auto_20200127_1233'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tuninglist',
            old_name='expect_sql_text',
            new_name='expect_elapsed_time',
        ),
    ]
