# Generated by Django 2.1.5 on 2020-01-27 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0057_auto_20200127_1234'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tuninglist',
            name='asis_elapsed_time',
            field=models.FloatField(null=True, verbose_name='튜닝 전 수행 시간'),
        ),
        migrations.AlterField(
            model_name='tuninglist',
            name='expect_elapsed_time',
            field=models.FloatField(null=True, verbose_name='기대 수행 시간'),
        ),
        migrations.AlterField(
            model_name='tuninglist',
            name='tobe_elapsed_time',
            field=models.FloatField(blank=True, null=True, verbose_name='튜닝 후 수행 시간'),
        ),
    ]
