# Generated by Django 2.1.5 on 2020-01-27 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0058_auto_20200127_1245'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tuninglist',
            name='asis_sql_text',
            field=models.TextField(null=True, verbose_name='튜닝전SQL'),
        ),
        migrations.AlterField(
            model_name='tuninglist',
            name='tobe_sql_text',
            field=models.TextField(blank=True, null=True, verbose_name='튜닝후SQL(튜너 작성)'),
        ),
        migrations.AlterField(
            model_name='tuninglist',
            name='tuning_info',
            field=models.TextField(blank=True, max_length=10000, null=True, verbose_name='튜너의견(튜너 작성)'),
        ),
    ]
