# Generated by Django 2.1.5 on 2020-01-27 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0059_auto_20200127_1418'),
    ]

    operations = [
        migrations.AddField(
            model_name='tuninglist',
            name='asis_plan',
            field=models.TextField(null=True, verbose_name='튜닝전\tPlan(튜너 작성)'),
        ),
        migrations.AddField(
            model_name='tuninglist',
            name='tobe_plan',
            field=models.TextField(null=True, verbose_name='튜닝후 Plan(튜너 작성)'),
        ),
    ]
