# Generated by Django 2.1.5 on 2020-01-27 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0060_auto_20200127_1420'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tuninglist',
            name='asis_plan',
            field=models.TextField(blank=True, null=True, verbose_name='튜닝전\tPlan(튜너 작성)'),
        ),
        migrations.AlterField(
            model_name='tuninglist',
            name='tobe_plan',
            field=models.TextField(blank=True, null=True, verbose_name='튜닝후 Plan(튜너 작성)'),
        ),
    ]
