# Generated by Django 2.1.5 on 2020-01-27 15:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0061_auto_20200127_1424'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datalist',
            name='data_explain',
            field=models.TextField(max_length=4000, null=True, verbose_name='설명'),
        ),
        migrations.AlterField(
            model_name='datalist',
            name='data_title',
            field=models.CharField(max_length=1000, null=True, verbose_name='제목'),
        ),
        migrations.AlterField(
            model_name='datalist',
            name='id_dblist',
            field=models.ForeignKey(db_column='id_dblist', null=True, on_delete=django.db.models.deletion.PROTECT, to='database.DbList', verbose_name='DB명'),
        ),
        migrations.AlterField(
            model_name='datalist',
            name='privacy_yn',
            field=models.CharField(choices=[('1', 'Y'), ('0', 'N')], default='0', max_length=100, null=True, verbose_name='개인정보유무'),
        ),
        migrations.AlterField(
            model_name='datalist',
            name='realoretl',
            field=models.CharField(choices=[('1', '실시간'), ('0', '분석')], default='0', max_length=100, null=True, verbose_name='실시간or분석'),
        ),
        migrations.AlterField(
            model_name='datalist',
            name='sql_text',
            field=models.TextField(help_text=' <font color=red><b>help</b></font><br>":"로 바인딩하여 SQL을 작성하면 동적으로 파라메터 값을 받을 수 있습니다. 예를들면, :상픔코드, :주문일자 와 같이 바인딩 사용 시 사용자가 SQL을 실행할 때 상품코드와 주문일자를 입력할 수 있습니다.', max_length=10000, null=True, verbose_name='관련SQL'),
        ),
    ]
