# Generated by Django 2.1.5 on 2020-01-27 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0062_auto_20200127_1500'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datalist',
            name='exp_yn',
            field=models.CharField(choices=[('1', 'Y'), ('0', 'N')], default='0', max_length=100, null=True, verbose_name='노출여부'),
        ),
    ]
