# Generated by Django 2.1.5 on 2020-01-28 22:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0063_auto_20200127_2030'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userexecutesql',
            name='id_reg_user',
        ),
        migrations.AlterField(
            model_name='datalist',
            name='sql_text',
            field=models.TextField(help_text=' <b>* help *</b><br>":"로 바인딩하여 SQL을 작성하면 동적으로 파라메터 값을 받을 수 있습니다. 예를들면, :상픔코드, :주문일자 와 같이 바인딩 사용 시 사용자가 SQL을 실행할 때 상품코드와 주문일자를 입력할 수 있습니다.<br><font color=red>주의: :yyyy :mm :dd :hh :mi :ss :digit 등은 바인드 변수로 사용할 수 없습니다.</font>', max_length=10000, null=True, verbose_name='관련SQL'),
        ),
        migrations.DeleteModel(
            name='UserExecuteSQL',
        ),
    ]
