# Generated by Django 2.1.5 on 2020-01-28 22:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0064_auto_20200128_2237'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserExecuteSQL',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sql_text', models.TextField(default='SELECT 1 FROM DUAL', max_length=10000, verbose_name='관련SQL')),
                ('id_reg_user', models.TextField(max_length=1000, verbose_name='수행자')),
                ('reg_dtm', models.DateTimeField(auto_now_add=True, verbose_name='등록일자')),
                ('execute_time', models.FloatField(blank=True, null=True, verbose_name='수행시간')),
                ('id_datalist', models.CharField(blank=True, max_length=100, null=True, verbose_name='데이터리스트')),
            ],
            options={
                'verbose_name': '[z99] 사용자 실행SQL',
                'verbose_name_plural': '[z99] 사용자 실행SQL',
                'db_table': 'cust_user_execute_sql',
            },
        ),
    ]
