# Generated by Django 2.1.5 on 2020-01-28 22:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0065_userexecutesql'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userexecutesql',
            name='sql_text',
            field=models.TextField(default='SELECT 1 FROM DUAL', verbose_name='관련SQL'),
        ),
    ]
