# Generated by Django 2.1.5 on 2020-01-29 21:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0067_auto_20200129_2147'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='datalist',
            name='prov_yn1_dtm',
        ),
        migrations.RemoveField(
            model_name='datalist',
            name='prov_yn2_dtm',
        ),
    ]
