# Generated by Django 2.1.5 on 2020-01-29 21:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0068_auto_20200129_2149'),
    ]

    operations = [
        migrations.AddField(
            model_name='datalist',
            name='prov_yn1_dtm',
            field=models.DateTimeField(null=True, verbose_name='보안 승인 일자'),
        ),
        migrations.AddField(
            model_name='datalist',
            name='prov_yn2_dtm',
            field=models.DateTimeField(null=True, verbose_name='성능 승인 일자'),
        ),
    ]
