# Generated by Django 2.1.5 on 2020-01-29 21:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0069_auto_20200129_2149'),
    ]

    operations = [
        migrations.AddField(
            model_name='datalist',
            name='prov_yn1_text',
            field=models.TextField(blank=True, help_text='반려 시 사유를 작성해주세요.', null=True, verbose_name='반려사유'),
        ),
        migrations.AddField(
            model_name='datalist',
            name='prov_yn2_text',
            field=models.TextField(blank=True, help_text='반려 시 사유를 작성해주세요.', null=True, verbose_name='반려사유'),
        ),
        migrations.AlterField(
            model_name='datalist',
            name='prov_yn1',
            field=models.CharField(choices=[('1', '승인'), ('0', '승인대기'), ('-1', '반려')], default='0', max_length=100, null=True, verbose_name='보안 승인여부'),
        ),
        migrations.AlterField(
            model_name='datalist',
            name='prov_yn2',
            field=models.CharField(choices=[('1', '승인'), ('0', '승인대기'), ('-1', '반려')], default='0', max_length=100, null=True, verbose_name='성능 승인여부'),
        ),
    ]
