# Generated by Django 2.1.5 on 2020-02-16 18:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0072_auto_20200216_1727'),
    ]

    operations = [
        migrations.AddField(
            model_name='datarequest',
            name='prov_yn',
            field=models.CharField(choices=[('1', '승인'), ('0', '승인대기'), ('2', '반려')], default='0', max_length=100, null=True, verbose_name='승인여부'),
        ),
        migrations.AlterField(
            model_name='datarequest',
            name='id_prov_user',
            field=models.ForeignKey(blank=True, db_column='id_prov_user', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='User_DataRequest_prov_user1', to=settings.AUTH_USER_MODEL, verbose_name='승인자'),
        ),
    ]
