# Generated by Django 2.1.5 on 2020-02-22 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0075_auto_20200217_1233'),
    ]

    operations = [
        migrations.AddField(
            model_name='dblist',
            name='eos_explain',
            field=models.TextField(blank=True, max_length=4000, null=True, verbose_name='EOS조치방안'),
        ),
        migrations.AddField(
            model_name='dblist',
            name='eos_yn',
            field=models.CharField(blank=True, choices=[('1', 'Y'), ('0', 'N')], default='0', max_length=30, null=True, verbose_name='EOS여부'),
        ),
    ]
