# Generated by Django 2.1.5 on 2020-02-22 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0076_auto_20200222_1012'),
    ]

    operations = [
        migrations.AddField(
            model_name='dblist',
            name='eos_dt',
            field=models.DateTimeField(blank=True, null=True, verbose_name='EOS일자'),
        ),
    ]
