# Generated by Django 2.1.5 on 2020-02-22 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0077_dblist_eos_dt'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dblist',
            name='eos_dt',
            field=models.DateField(blank=True, null=True, verbose_name='EOS일자'),
        ),
    ]
