# Generated by Django 2.1.5 on 2020-02-22 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0078_auto_20200222_1129'),
    ]

    operations = [
        migrations.AddField(
            model_name='dblist',
            name='db_typ',
            field=models.CharField(blank=True, choices=[('1', 'ORACLE'), ('2', 'MySQL'), ('3', 'MariaDB'), ('4', 'PostgreSQL'), ('5', 'MSSQL'), ('6', 'SybaseIQ')], default='1', max_length=30, null=True, verbose_name='DBMS종류'),
        ),
        migrations.AddField(
            model_name='dblist',
            name='db_ver',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='DBMS버전'),
        ),
    ]
