# Generated by Django 2.1.5 on 2020-02-22 11:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0079_auto_20200222_1138'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dbdetail',
            name='db_typ',
        ),
        migrations.RemoveField(
            model_name='dbdetail',
            name='db_ver',
        ),
    ]
