# Generated by Django 2.1.5 on 2020-02-24 09:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('database', '0080_auto_20200222_1143'),
    ]

    operations = [
        migrations.AddField(
            model_name='dblist',
            name='id_manager',
            field=models.ForeignKey(blank=True, db_column='id_manager', null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='담당자'),
        ),
    ]
