# Generated by Django 2.1.5 on 2020-02-24 10:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('database', '0081_dblist_id_manager'),
    ]

    operations = [
        migrations.CreateModel(
            name='DbPosition',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.CharField(blank=True, max_length=100, null=True, verbose_name='DBMS종류')),
                ('reg_dtm', models.DateTimeField(auto_now_add=True, null=True, verbose_name='등록일자')),
                ('id_reg_user', models.ForeignKey(blank=True, db_column='id_reg_user', null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='등록자')),
            ],
            options={
                'verbose_name': '[DBA-00] DBMS 위치',
                'verbose_name_plural': '[DBA-00] DBMS 위치',
                'db_table': 'cust_db_position',
            },
        ),
        migrations.CreateModel(
            name='DbType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('db_type', models.CharField(blank=True, max_length=100, null=True, verbose_name='DBMS종류')),
                ('reg_dtm', models.DateTimeField(auto_now_add=True, null=True, verbose_name='등록일자')),
                ('id_reg_user', models.ForeignKey(blank=True, db_column='id_reg_user', null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='등록자')),
            ],
            options={
                'verbose_name': '[DBA-00] DBMS 종류',
                'verbose_name_plural': '[DBA-00] DBMS 종류',
                'db_table': 'cust_db_type',
            },
        ),
        migrations.AddField(
            model_name='dblist',
            name='id_dbposition',
            field=models.ForeignKey(blank=True, db_column='id_dbposition', null=True, on_delete=django.db.models.deletion.PROTECT, to='database.DbPosition', verbose_name='DBMS위치'),
        ),
        migrations.AddField(
            model_name='dblist',
            name='id_dbtype',
            field=models.ForeignKey(blank=True, db_column='id_dbtype', null=True, on_delete=django.db.models.deletion.PROTECT, to='database.DbType', verbose_name='DBMS종류'),
        ),
    ]
