# Generated by Django 2.1.5 on 2020-02-24 10:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0082_auto_20200224_1013'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dblist',
            name='db_typ',
        ),
    ]
