# Generated by Django 2.1.5 on 2020-02-24 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0083_remove_dblist_db_typ'),
    ]

    operations = [
        migrations.AddField(
            model_name='dbdetail',
            name='use_yn',
            field=models.CharField(blank=True, choices=[('1', 'Y'), ('0', 'N')], default='1', max_length=30, null=True, verbose_name='사용여부'),
        ),
        migrations.AddField(
            model_name='dblist',
            name='use_yn',
            field=models.CharField(blank=True, choices=[('1', 'Y'), ('0', 'N')], default='1', max_length=30, null=True, verbose_name='사용여부'),
        ),
        migrations.AlterField(
            model_name='dbdetail',
            name='db_nm',
            field=models.CharField(blank=True, max_length=100, verbose_name='DB명'),
        ),
        migrations.AlterField(
            model_name='dbdetail',
            name='host_nm',
            field=models.CharField(blank=True, max_length=100, verbose_name='호스트명'),
        ),
        migrations.AlterField(
            model_name='dbdetail',
            name='inst_nm',
            field=models.CharField(blank=True, max_length=100, verbose_name='인스턴스명'),
        ),
        migrations.AlterField(
            model_name='dbdetail',
            name='tns_desc',
            field=models.TextField(blank=True, max_length=4000, null=True, verbose_name='DB접속정보(TNS,EndPoint등)'),
        ),
        migrations.AlterField(
            model_name='dbposition',
            name='position',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='DBMS위치'),
        ),
    ]
