# Generated by Django 2.1.5 on 2020-02-24 20:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0084_auto_20200224_1116'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uservisit',
            name='id_menulist',
            field=models.ForeignKey(blank=True, db_column='id_menulist', null=True, on_delete=django.db.models.deletion.CASCADE, to='database.MenuList', verbose_name='메뉴리스트'),
        ),
    ]
