# Generated by Django 2.1.5 on 2020-03-04 21:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('database', '0085_auto_20200224_2023'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('db_use', models.CharField(blank=True, max_length=100, null=True, verbose_name='db용도')),
                ('oper_cd', models.CharField(blank=True, choices=[('1', '관리'), ('2', '현행화'), ('3', '운영'), ('4', '개발')], default='3', max_length=30, null=True, verbose_name='운영구분')),
                ('username', models.CharField(blank=True, max_length=100, null=True, verbose_name='계정명')),
                ('status', models.CharField(blank=True, choices=[('1', '관리'), ('2', '현행화'), ('3', '운영'), ('4', '개발')], default='0', max_length=100, null=True, verbose_name='계정상태')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='생성일자')),
                ('profile', models.CharField(blank=True, max_length=100, null=True, verbose_name='프로파일명')),
                ('reg_dtm', models.DateTimeField(auto_now_add=True, verbose_name='등록일자')),
                ('mod_dtm', models.DateTimeField(auto_now=True, verbose_name='수정일자')),
                ('id_dblist', models.ForeignKey(db_column='id_dblist', on_delete=django.db.models.deletion.PROTECT, to='database.DbList', verbose_name='DB명')),
                ('id_user_name', models.ForeignKey(blank=True, db_column='id_user_name', null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='이름')),
            ],
            options={
                'verbose_name': '[DBA-99] User 리스트',
                'verbose_name_plural': '[DBA-99] User 리스트',
                'db_table': 'cust_user_list',
            },
        ),
        migrations.AlterField(
            model_name='datarequest',
            name='data_input',
            field=models.CharField(blank=True, max_length=1000, null=True, verbose_name='입력값'),
        ),
        migrations.AlterField(
            model_name='tuninglist',
            name='bind_value',
            field=models.TextField(blank=True, help_text='SQL에 바인딩되는 값을 꼭 입력해주세요', max_length=500, null=True, verbose_name='바인딩값'),
        ),
    ]
