# Generated by Django 2.1.5 on 2020-03-06 14:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('database', '0087_auto_20200306_1209'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserRequestAccountOpenHist',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('approv_dtm', models.DateTimeField(auto_now_add=True, verbose_name='승인일자')),
                ('reg_dtm', models.DateTimeField(auto_now_add=True, verbose_name='등록일자')),
                ('id_approver', models.ForeignKey(blank=True, db_column='id_approver', null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='승인자')),
                ('id_reg_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='id_reg_user', to=settings.AUTH_USER_MODEL, verbose_name='등록자')),
                ('id_userlist', models.ForeignKey(db_column='id_userlist', on_delete=django.db.models.deletion.PROTECT, to='database.UserList', verbose_name='User명')),
            ],
            options={
                'verbose_name': '[DBA-99] 계정활성화신청이력',
                'verbose_name_plural': '[DBA-99] 계정활성화신청이력',
                'db_table': 'cust_user_request_account_open_hist',
            },
        ),
        migrations.RemoveField(
            model_name='userrequestaccountopen',
            name='id_approver',
        ),
        migrations.RemoveField(
            model_name='userrequestaccountopen',
            name='id_reg_user',
        ),
        migrations.RemoveField(
            model_name='userrequestaccountopen',
            name='id_userlist',
        ),
        migrations.DeleteModel(
            name='UserRequestAccountOpen',
        ),
    ]
