# Generated by Django 2.1.5 on 2020-03-06 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0088_auto_20200306_1430'),
    ]

    operations = [
        migrations.AddField(
            model_name='userlist',
            name='request_status',
            field=models.CharField(blank=True, choices=[('0', 'OPEN'), ('1', '신청중')], default='0', max_length=100, null=True, verbose_name='신청상태'),
        ),
    ]
