# Generated by Django 2.1.5 on 2020-03-06 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0089_userlist_request_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userrequestaccountopenhist',
            name='approv_dtm',
            field=models.DateTimeField(verbose_name='승인일자'),
        ),
    ]
