# Generated by Django 2.1.5 on 2020-03-06 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0090_auto_20200306_1556'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userrequestaccountopenhist',
            name='approv_dtm',
            field=models.DateTimeField(blank=True, null=True, verbose_name='승인일자'),
        ),
    ]
