# Generated by Django 2.1.5 on 2020-03-06 22:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0091_auto_20200306_1556'),
    ]

    operations = [
        migrations.CreateModel(
            name='OperCd',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('oper_cd', models.CharField(default='', max_length=100, verbose_name='운영구분')),
            ],
            options={
                'verbose_name': '[DBA-99] 운영구분 (운영/개발/....)',
                'verbose_name_plural': '[DBA-99] 운영구분 (운영/개발/....)',
                'db_table': 'cust_oper_cd',
            },
        ),
        migrations.AlterField(
            model_name='userlist',
            name='id_dblist',
            field=models.ForeignKey(blank=True, db_column='id_dblist', on_delete=django.db.models.deletion.PROTECT, to='database.DbList', verbose_name='DB명'),
        ),
    ]
