# Generated by Django 2.1.5 on 2020-03-06 22:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0092_auto_20200306_2224'),
    ]

    operations = [
        migrations.AlterField(
            model_name='columnlist',
            name='oper_cd',
            field=models.ForeignKey(blank=True, db_column='oper_cd', null=True, on_delete=django.db.models.deletion.PROTECT, to='database.OperCd', verbose_name='운영구분'),
        ),
        migrations.AlterField(
            model_name='dbdetail',
            name='oper_cd',
            field=models.ForeignKey(blank=True, db_column='oper_cd', null=True, on_delete=django.db.models.deletion.PROTECT, to='database.OperCd', verbose_name='운영구분'),
        ),
        migrations.AlterField(
            model_name='tablelist',
            name='oper_cd',
            field=models.ForeignKey(blank=True, db_column='oper_cd', null=True, on_delete=django.db.models.deletion.PROTECT, to='database.OperCd', verbose_name='운영구분'),
        ),
        migrations.AlterField(
            model_name='userlist',
            name='oper_cd',
            field=models.ForeignKey(blank=True, db_column='oper_cd', null=True, on_delete=django.db.models.deletion.PROTECT, to='database.OperCd', verbose_name='운영구분'),
        ),
    ]
