# Generated by Django 2.1.5 on 2020-03-06 22:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0093_auto_20200306_2240'),
    ]

    operations = [
        migrations.CreateModel(
            name='DBMS',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dbms_type', models.CharField(default='', max_length=100, verbose_name='DBMS종류')),
            ],
            options={
                'verbose_name': '[DBA-99] DBMS종류 (ORACLE/MYSQL/....)',
                'verbose_name_plural': '[DBA-99] DBMS종류 (ORACLE/MYSQL/....)',
                'db_table': 'cust_dbms',
            },
        ),
    ]
