# Generated by Django 2.1.5 on 2020-03-06 22:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0094_dbms'),
    ]

    operations = [
        migrations.DeleteModel(
            name='DBMS',
        ),
    ]
