# Generated by Django 2.1.5 on 2020-03-06 22:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0095_delete_dbms'),
    ]

    operations = [
        migrations.AddField(
            model_name='batchlist',
            name='id_dbtype',
            field=models.ForeignKey(blank=True, db_column='id_dbtype', null=True, on_delete=django.db.models.deletion.PROTECT, to='database.DbType', verbose_name='DBMS종류'),
        ),
    ]
