# Generated by Django 2.1.5 on 2020-03-06 22:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0096_batchlist_id_dbtype'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='batchlist',
            name='dbms_type',
        ),
    ]
