# Generated by Django 2.1.5 on 2020-03-07 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0097_remove_batchlist_dbms_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='dblist',
            name='gather_meta_yn',
            field=models.CharField(blank=True, choices=[('1', 'Y'), ('0', 'N')], default='0', max_length=30, null=True, verbose_name='메타정보수집여부'),
        ),
    ]
