# Generated by Django 2.1.5 on 2020-03-07 22:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0098_dblist_gather_meta_yn'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tablelist',
            name='id_dblist',
            field=models.ForeignKey(blank=True, db_column='id_dblist', on_delete=django.db.models.deletion.PROTECT, to='database.DbList', verbose_name='DB명'),
        ),
    ]
