# Generated by Django 2.1.5 on 2020-03-09 11:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0100_auto_20200309_1139'),
    ]

    operations = [
        migrations.AddField(
            model_name='userrequesttabprivhist',
            name='id_tablelist',
            field=models.ForeignKey(db_column='id_tablelist', default=100, on_delete=django.db.models.deletion.PROTECT, to='database.TableList', verbose_name='Table명'),
            preserve_default=False,
        ),
    ]
