# Generated by Django 2.1.5 on 2020-03-09 13:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0102_userrequesttabprivhist_approv_yn'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userrequesttabprivhist',
            name='id_tablelist',
            field=models.ForeignKey(db_column='id_tablelist', null=True, on_delete=django.db.models.deletion.PROTECT, to='database.TableList', verbose_name='Table명'),
        ),
    ]
