# Generated by Django 2.1.5 on 2020-03-14 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0105_auto_20200311_1645'),
    ]

    operations = [
        migrations.AlterField(
            model_name='columnlist',
            name='column_name',
            field=models.CharField(max_length=100, null=True, verbose_name='컬럼명'),
        ),
        migrations.AlterField(
            model_name='datalist',
            name='data_title',
            field=models.CharField(blank=True, max_length=1000, null=True, verbose_name='제목'),
        ),
        migrations.AlterField(
            model_name='datalist',
            name='mod_dtm',
            field=models.DateTimeField(blank=True, null=True, verbose_name='수정일자'),
        ),
    ]
