
# Generated by Django 2.1.5 on 2020-03-14 23:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0106_auto_20200314_1120'),
    ]

    operations = [
        migrations.AddField(
            model_name='tuninglist',
            name='daily_exec_cnt',
            field=models.IntegerField(null=True, verbose_name='일 실행 횟수'),
        ),
        migrations.AlterField(
            model_name='datalist',
            name='privacy_yn',
            field=models.CharField(choices=[('1', '존재'), ('0', '없음')], default='0', help_text='개인정보를 조회하는 경우 보안센터 승인을 받은 후 수행할 수 있습니다.', max_length=100, null=True, verbose_name='개인정보유무'),
        ),
        migrations.AlterField(
            model_name='tuninglist',
            name='asis_elapsed_time',
            field=models.FloatField(null=True, verbose_name='튜닝 전 응답 시간(초)'),
        ),
        migrations.AlterField(
            model_name='tuninglist',
            name='expect_elapsed_time',
            field=models.FloatField(null=True, verbose_name='튜닝 후 기대 응답 시간(초)'),
        ),
        migrations.AlterField(
            model_name='tuninglist',
            name='id_dblist',
            field=models.ForeignKey(db_column='id_dblist', null=True, on_delete=django.db.models.deletion.PROTECT, to='database.DbList', verbose_name='DB명'),
        ),
        migrations.AlterField(
            model_name='tuninglist',
            name='id_domain',
            field=models.ForeignKey(db_column='id_domain', null=True, on_delete=django.db.models.deletion.PROTECT, to='database.Domain', verbose_name='업무도메인명'),
        ),
        migrations.AlterField(
            model_name='tuninglist',
            name='id_tuningstatus',
            field=models.ForeignKey(db_column='id_tuningstatus', default='1', null=True, on_delete=django.db.models.deletion.PROTECT, to='database.TuningStatus', verbose_name='튜닝진행상태'),
        ),
        migrations.AlterField(
            model_name='tuninglist',
            name='sql_type',
            field=models.CharField(choices=[('1', '운영-온라인/신규'), ('2', '운영-온라인/변경'), ('3', '운영-배치/신규'), ('4', '운영-배치/변경'), ('5', '분석-신규'), ('6', '분석-배치'), ('7', '기타')], default='0', max_length=30, verbose_name='신규or변경'),
        ),
    ]
