# Generated by Django 2.1.5 on 2020-03-16 17:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0107_auto_20200314_2357'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='datarequest',
            name='data_input',
        ),
        migrations.AlterField(
            model_name='datarequest',
            name='data_explain',
            field=models.TextField(blank=True, null=True, verbose_name='필요사유'),
        ),
        migrations.AlterField(
            model_name='datarequest',
            name='mod_dtm',
            field=models.DateTimeField(blank=True, null=True, verbose_name='수정일자'),
        ),
        migrations.AlterField(
            model_name='tuninglist',
            name='mod_dtm',
            field=models.DateTimeField(blank=True, null=True, verbose_name='수정일자'),
        ),
        migrations.AlterField(
            model_name='userlist',
            name='id_dblist',
            field=models.ForeignKey(blank=True, db_column='id_dblist', on_delete=django.db.models.deletion.CASCADE, to='database.DbList', verbose_name='DB명'),
        ),
        migrations.AlterField(
            model_name='userrequestaccountopenhist',
            name='id_userlist',
            field=models.ForeignKey(db_column='id_userlist', on_delete=django.db.models.deletion.CASCADE, to='database.UserList', verbose_name='User명'),
        ),
    ]
