# Generated by Django 2.1.5 on 2020-03-17 11:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0109_objectlist'),
    ]

    operations = [
        migrations.CreateModel(
            name='ObjectSource',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('db_use', models.CharField(blank=True, max_length=100, null=True, verbose_name='db용도')),
                ('reg_dtm', models.DateTimeField(auto_now_add=True, verbose_name='등록일자')),
                ('owner', models.CharField(max_length=100, verbose_name='소유자')),
                ('object_name', models.CharField(blank=True, max_length=100, verbose_name='오브젝트명')),
                ('object_type', models.CharField(blank=True, max_length=100, verbose_name='오브젝트타입')),
                ('line', models.IntegerField(blank=True, null=True, verbose_name='순서')),
                ('status', models.CharField(blank=True, max_length=100, verbose_name='상태')),
                ('text', models.TextField(blank=True, null=True, verbose_name='소스')),
                ('id_objectlist', models.ForeignKey(blank=True, db_column='id_dblist', on_delete=django.db.models.deletion.PROTECT, to='database.ObjectList', verbose_name='오브젝트명ID')),
                ('oper_cd', models.ForeignKey(blank=True, db_column='oper_cd', null=True, on_delete=django.db.models.deletion.PROTECT, to='database.OperCd', verbose_name='운영구분')),
            ],
            options={
                'verbose_name': '[DBA-99] Object 소스',
                'verbose_name_plural': '[DBA-99] Object 소스',
                'db_table': 'cust_object_source',
            },
        ),
    ]
