# Generated by Django 2.1.5 on 2020-03-17 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0110_objectsource'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='objectlist',
            name='drop_yn',
        ),
        migrations.AddField(
            model_name='objectlist',
            name='created',
            field=models.DateTimeField(blank=True, null=True, verbose_name='생성일자'),
        ),
        migrations.AddField(
            model_name='objectlist',
            name='last_ddl_time',
            field=models.DateTimeField(blank=True, null=True, verbose_name='변경일자'),
        ),
    ]
