# Generated by Django 2.1.5 on 2020-03-17 12:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0114_batchlist_truncate_yn'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='objectsource',
            name='status',
        ),
        migrations.AlterField(
            model_name='objectsource',
            name='id_objectlist',
            field=models.ForeignKey(blank=True, db_column='id_objectlist', on_delete=django.db.models.deletion.DO_NOTHING, to='database.ObjectList', verbose_name='오브젝트명ID'),
        ),
    ]
