# Generated by Django 2.1.5 on 2020-03-19 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0117_auto_20200317_1337'),
    ]

    operations = [
        migrations.AddField(
            model_name='userrequesttabprivhist',
            name='object_type',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='오브젝트타입'),
        ),
    ]
