# Generated by Django 2.1.5 on 2020-03-19 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0118_userrequesttabprivhist_object_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userrequesttabprivhist',
            name='id_tablelist',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='오브젝트번호'),
        ),
    ]
