# Generated by Django 2.1.5 on 2020-03-19 21:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0120_auto_20200319_2131'),
    ]

    operations = [
        migrations.AddField(
            model_name='objectlist',
            name='subobject_name',
            field=models.CharField(blank=True, max_length=100, verbose_name='서브오브젝트'),
        ),
    ]
