# Generated by Django 2.1.5 on 2020-03-19 22:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0121_objectlist_subobject_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='objectlist',
            name='subobject_name',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='서브오브젝트'),
        ),
    ]
