# Generated by Django 2.1.5 on 2020-03-20 00:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0122_auto_20200319_2227'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userrequesttabprivhist',
            name='id_tablelist',
        ),
        migrations.AddField(
            model_name='userrequesttabprivhist',
            name='id_objectlist',
            field=models.ForeignKey(blank=True, db_column='id_obejctlist', null=True, on_delete=django.db.models.deletion.CASCADE, to='database.ObjectList', verbose_name='오브젝트명'),
        ),
        migrations.AlterField(
            model_name='userrequestaccountopenhist',
            name='id_approver',
            field=models.ForeignKey(blank=True, db_column='id_approver', null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='승인자'),
        ),
        migrations.AlterField(
            model_name='userrequestaccountopenhist',
            name='id_reg_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='id_reg_user', to=settings.AUTH_USER_MODEL, verbose_name='등록자'),
        ),
        migrations.AlterField(
            model_name='userrequesttabprivhist',
            name='id_approver',
            field=models.ForeignKey(blank=True, db_column='id_approver', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='id_approver_priv', to=settings.AUTH_USER_MODEL, verbose_name='승인자'),
        ),
        migrations.AlterField(
            model_name='userrequesttabprivhist',
            name='id_reg_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='id_reg_user_priv', to=settings.AUTH_USER_MODEL, verbose_name='등록자'),
        ),
        migrations.AlterField(
            model_name='userrequesttabprivhist',
            name='id_userlist',
            field=models.ForeignKey(blank=True, db_column='id_userlist', null=True, on_delete=django.db.models.deletion.CASCADE, to='database.UserList', verbose_name='User명'),
        ),
    ]
