# Generated by Django 2.1.5 on 2020-03-23 18:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('database', '0124_metagrantlist'),
    ]

    operations = [
        migrations.CreateModel(
            name='DB_USER',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('db_username', models.OneToOneField(db_column='db_username', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '[DBA-99] DB USER 매핑',
                'verbose_name_plural': '[DBA-99] DB USER 매핑',
                'db_table': 'cust_db_user',
            },
        ),
    ]
