# Generated by Django 2.1.5 on 2020-03-23 18:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0125_db_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='db_user',
            name='db_username',
        ),
        migrations.DeleteModel(
            name='DB_USER',
        ),
    ]
