# Generated by Django 2.1.5 on 2020-03-23 18:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0127_dbuser'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dbuser',
            name='db_username',
        ),
        migrations.DeleteModel(
            name='DBUser',
        ),
    ]
