# Generated by Django 2.1.5 on 2020-03-23 18:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('database', '0128_auto_20200323_1839'),
    ]

    operations = [
        migrations.CreateModel(
            name='SabunDBUserMapping',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('db_username', models.CharField(default='', max_length=100, verbose_name='DB명')),
                ('id_userlist', models.OneToOneField(db_column='id_userlist', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '[DBA-99] DB USER 매핑',
                'verbose_name_plural': '[DBA-99] DB USER 매핑',
                'db_table': 'cust_sabun_dbuser_mapping',
            },
        ),
    ]
