# Generated by Django 2.1.5 on 2020-03-24 11:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('database', '0129_sabundbusermapping'),
    ]

    operations = [
        migrations.CreateModel(
            name='GrantList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reg_dtm', models.DateTimeField(auto_now_add=True, null=True, verbose_name='등록일자')),
                ('grantee', models.CharField(blank=True, max_length=100, null=True, verbose_name='grantee')),
                ('owner', models.CharField(blank=True, max_length=100, null=True, verbose_name='owner')),
                ('table_name', models.CharField(blank=True, max_length=100, null=True, verbose_name='table_name')),
                ('privilege', models.CharField(blank=True, max_length=100, null=True, verbose_name='privilege')),
                ('granted_role', models.CharField(blank=True, max_length=100, null=True, verbose_name='granted_role')),
                ('id_dblist', models.ForeignKey(db_column='id_dblist', null=True, on_delete=django.db.models.deletion.PROTECT, to='database.DbList', verbose_name='DB명')),
                ('id_reg_user', models.ForeignKey(blank=True, db_column='id_reg_user', null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='등록자')),
                ('oper_cd', models.ForeignKey(blank=True, db_column='oper_cd', null=True, on_delete=django.db.models.deletion.PROTECT, to='database.OperCd', verbose_name='운영구분')),
            ],
            options={
                'verbose_name': '[DBA-99] 권한 리스트',
                'verbose_name_plural': '[DBA-99] 권한 리스트',
                'db_table': 'cust_grant_list',
            },
        ),
    ]
