# Generated by Django 2.1.5 on 2020-03-24 11:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0130_grantlist'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='grantlist',
            name='id_reg_user',
        ),
    ]
