# Generated by Django 2.1.5 on 2020-03-26 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0133_auto_20200325_2047'),
    ]

    operations = [
        migrations.CreateModel(
            name='WORD',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('std_wd_kor', models.CharField(default='', max_length=100, verbose_name='한글단어명')),
                ('std_wd_eng', models.CharField(default='', max_length=100, verbose_name='영문단어명')),
                ('std_wd_eng_ful', models.CharField(default='', max_length=100, verbose_name='영문FULL명')),
                ('expl', models.CharField(default='', max_length=100, verbose_name='설명')),
            ],
            options={
                'verbose_name': '[DBA-99] 표준단어',
                'verbose_name_plural': '[DBA-99] 표준단어',
                'db_table': 'cust_word',
            },
        ),
    ]
