# Generated by Django 2.1.5 on 2020-03-26 17:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0137_auto_20200326_1742'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stddomain',
            name='id_std_domaintype',
        ),
        migrations.DeleteModel(
            name='StdDomain',
        ),
    ]
