# Generated by Django 2.1.5 on 2020-03-27 08:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0139_stddomain'),
    ]

    operations = [
        migrations.RenameField(
            model_name='stddomain',
            old_name='data_type',
            new_name='oracle_data_type',
        ),
        migrations.RenameField(
            model_name='stddomain',
            old_name='decimal_leng',
            new_name='oracle_decimal_leng',
        ),
        migrations.RenameField(
            model_name='stddomain',
            old_name='leng',
            new_name='oracle_leng',
        ),
    ]
