# Generated by Django 2.1.5 on 2020-03-27 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0140_auto_20200327_0857'),
    ]

    operations = [
        migrations.AddField(
            model_name='stddomain',
            name='mysql_data_type',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='데이터타입'),
        ),
        migrations.AddField(
            model_name='stddomain',
            name='mysql_decimal_leng',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='데이터길이'),
        ),
        migrations.AddField(
            model_name='stddomain',
            name='mysql_leng',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='데이터길이'),
        ),
    ]
