# Generated by Django 2.1.5 on 2020-03-28 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0141_auto_20200327_0919'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stddomain',
            name='mysql_decimal_leng',
            field=models.IntegerField(blank=True, null=True, verbose_name='데이터길이'),
        ),
        migrations.AlterField(
            model_name='stddomain',
            name='mysql_leng',
            field=models.IntegerField(blank=True, null=True, verbose_name='데이터길이'),
        ),
        migrations.AlterField(
            model_name='stddomain',
            name='oracle_decimal_leng',
            field=models.IntegerField(blank=True, null=True, verbose_name='데이터길이'),
        ),
        migrations.AlterField(
            model_name='stddomain',
            name='oracle_leng',
            field=models.IntegerField(blank=True, null=True, verbose_name='데이터길이'),
        ),
    ]
