# Generated by Django 2.1.5 on 2020-04-01 15:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('database', '0142_auto_20200328_2030'),
    ]

    operations = [
        migrations.CreateModel(
            name='MetaReqList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('column_id', models.IntegerField(blank=True, null=True, verbose_name='컬럼순서')),
                ('col_comments', models.CharField(blank=True, max_length=4000, null=True, verbose_name='컬럼코멘트')),
                ('pk_yn', models.CharField(blank=True, choices=[('1', 'Y'), ('0', 'N')], default='0', max_length=30, null=True, verbose_name='PK여부')),
                ('not_null', models.CharField(blank=True, choices=[('1', 'Y'), ('0', 'N')], default='0', max_length=30, null=True, verbose_name='NULL여부')),
                ('column_name', models.CharField(max_length=100, null=True, verbose_name='컬럼명')),
                ('data_type', models.CharField(blank=True, max_length=100, null=True, verbose_name='데이터타입')),
                ('change_list', models.CharField(max_length=100, null=True, verbose_name='변경사항')),
                ('change_reason', models.TextField(blank=True, null=True, verbose_name='비고')),
                ('reg_dtm', models.DateTimeField(auto_now_add=True, null=True, verbose_name='등록일자')),
                ('mod_dtm', models.DateTimeField(auto_now=True, null=True, verbose_name='수정일자')),
                ('id_reg_user', models.ForeignKey(blank=True, db_column='id_reg_user', null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='등록자')),
                ('id_tablelist', models.ForeignKey(blank=True, db_column='id_tablelist', max_length=100, null=True, on_delete=django.db.models.deletion.PROTECT, to='database.TableList', verbose_name='테이블명')),
            ],
            options={
                'verbose_name': '[DBA-99] 메타변경요청',
                'verbose_name_plural': '[DBA-99] 메타변경요청',
                'db_table': 'cust_meta_req_list',
            },
        ),
    ]
