# Generated by Django 2.1.5 on 2020-04-02 10:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('database', '0143_metareqlist'),
    ]

    operations = [
        migrations.CreateModel(
            name='MetaReq',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=4000, null=True, verbose_name='제목')),
                ('reg_dtm', models.DateTimeField(auto_now_add=True, null=True, verbose_name='등록일자')),
                ('mod_dtm', models.DateTimeField(auto_now=True, null=True, verbose_name='수정일자')),
                ('id_reg_user', models.ForeignKey(blank=True, db_column='id_reg_user', null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='등록자')),
                ('id_tablelist', models.ForeignKey(blank=True, db_column='id_tablelist', max_length=100, null=True, on_delete=django.db.models.deletion.PROTECT, to='database.TableList', verbose_name='테이블명')),
            ],
            options={
                'verbose_name': '[DBA-99] 메타변경요청',
                'verbose_name_plural': '[DBA-99] 메타변경요청',
                'db_table': 'cust_meta_req',
            },
        ),
        migrations.AlterModelOptions(
            name='metareqlist',
            options={'verbose_name': '[DBA-99] 메타변경요청상세', 'verbose_name_plural': '[DBA-99] 메타변경요청상세'},
        ),
        migrations.RemoveField(
            model_name='metareqlist',
            name='id_reg_user',
        ),
        migrations.RemoveField(
            model_name='metareqlist',
            name='mod_dtm',
        ),
        migrations.RemoveField(
            model_name='metareqlist',
            name='reg_dtm',
        ),
        migrations.AddField(
            model_name='metareqlist',
            name='id_metareq',
            field=models.ForeignKey(blank=True, db_column='id_metareq', max_length=100, null=True, on_delete=django.db.models.deletion.PROTECT, to='database.MetaReq', verbose_name='메타요청'),
        ),
    ]
