# Generated by Django 2.1.5 on 2020-04-02 23:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0144_auto_20200402_1019'),
    ]

    operations = [
        migrations.AddField(
            model_name='metareqlist',
            name='div',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='구분'),
        ),
        migrations.AlterField(
            model_name='metareq',
            name='mod_dtm',
            field=models.DateTimeField(blank=True, null=True, verbose_name='수정일자'),
        ),
    ]
