# Generated by Django 2.1.5 on 2020-04-03 09:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0146_metareqlist_id_dblist'),
    ]

    operations = [
        migrations.AddField(
            model_name='metareq',
            name='id_dblist',
            field=models.ForeignKey(blank=True, db_column='id_dblist', null=True, on_delete=django.db.models.deletion.PROTECT, to='database.DbList', verbose_name='DB명'),
        ),
    ]
