# Generated by Django 2.1.5 on 2020-04-03 10:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0147_metareq_id_dblist'),
    ]

    operations = [
        migrations.AlterField(
            model_name='metareq',
            name='id_dblist',
            field=models.ForeignKey(db_column='id_dblist', null=True, on_delete=django.db.models.deletion.PROTECT, to='database.DbList', verbose_name='DB명'),
        ),
    ]
