# Generated by Django 2.1.5 on 2020-04-03 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0148_auto_20200403_1002'),
    ]

    operations = [
        migrations.AddField(
            model_name='metareq',
            name='req_contents',
            field=models.TextField(blank=True, null=True, verbose_name='요청자 내용'),
        ),
    ]
