# Generated by Django 2.1.5 on 2020-04-03 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0149_metareq_req_contents'),
    ]

    operations = [
        migrations.AddField(
            model_name='metareq',
            name='table_comments',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='테이블 논리명'),
        ),
        migrations.AddField(
            model_name='metareq',
            name='table_name',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='테이블 물리명'),
        ),
        migrations.AlterField(
            model_name='metareq',
            name='req_contents',
            field=models.TextField(null=True, verbose_name='요청자 내용'),
        ),
        migrations.AlterField(
            model_name='metareq',
            name='title',
            field=models.CharField(max_length=200, null=True, verbose_name='제목'),
        ),
    ]
