# Generated by Django 2.1.5 on 2020-04-07 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0153_dbowner_id_dblist'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dbowner',
            name='owner',
            field=models.CharField(default='', max_length=100, verbose_name='노출User명'),
        ),
        migrations.AlterField(
            model_name='tuninglist',
            name='reg_dtm',
            field=models.DateTimeField(verbose_name='등록일자'),
        ),
        migrations.AlterModelTable(
            name='stdword',
            table='cust_std_word',
        ),
    ]
