# Generated by Django 2.1.5 on 2020-04-16 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0154_auto_20200407_1031'),
    ]

    operations = [
        migrations.AddField(
            model_name='metareqlist',
            name='privacy_list',
            field=models.CharField(blank=True, choices=[('0', '없음'), ('1', '고객'), ('2', '임직원')], default='0', max_length=30, null=True, verbose_name='개인정보'),
        ),
    ]
