# Generated by Django 2.1.5 on 2020-04-16 10:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0155_metareqlist_privacy_list'),
    ]

    operations = [
        migrations.AddField(
            model_name='metareq',
            name='id_domainanddblist',
            field=models.ForeignKey(blank=True, db_column='id_domainanddblist', null=True, on_delete=django.db.models.deletion.PROTECT, to='database.DomainAndDbList', verbose_name='도메인명'),
        ),
        migrations.AddField(
            model_name='metareq',
            name='storage_cycle',
            field=models.IntegerField(blank=True, null=True, verbose_name='보관주기'),
        ),
        migrations.AddField(
            model_name='metareq',
            name='storage_cycle_column',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='기준컬럼'),
        ),
        migrations.AlterField(
            model_name='metareqlist',
            name='privacy_list',
            field=models.CharField(blank=True, choices=[('0', ''), ('1', '고객'), ('2', '임직원')], default='0', max_length=30, null=True, verbose_name='개인정보'),
        ),
    ]
