# Generated by Django 2.1.5 on 2020-04-18 21:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0156_auto_20200416_1056'),
    ]

    operations = [
        migrations.AddField(
            model_name='metareq',
            name='id_da_dev',
            field=models.TextField(blank=True, null=True, verbose_name='DA 개발 시간'),
        ),
        migrations.AddField(
            model_name='metareq',
            name='id_dba_dev',
            field=models.TextField(blank=True, null=True, verbose_name='DBA 개발 승인 시간'),
        ),
        migrations.AddField(
            model_name='metareq',
            name='id_dba_prod',
            field=models.TextField(blank=True, null=True, verbose_name='DBA 운영 승인 시간'),
        ),
        migrations.AddField(
            model_name='metareq',
            name='id_pl_dev',
            field=models.TextField(blank=True, null=True, verbose_name='PL 개발 승인 시간'),
        ),
        migrations.AddField(
            model_name='metareq',
            name='id_pl_prod',
            field=models.TextField(blank=True, null=True, verbose_name='PL 운영 승인 시간'),
        ),
    ]
