# Generated by Django 2.1.5 on 2020-04-18 22:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0157_auto_20200418_2157'),
    ]

    operations = [
        migrations.AddField(
            model_name='metareq',
            name='da_dev_dtm',
            field=models.TextField(blank=True, null=True, verbose_name='DA 개발 시간'),
        ),
        migrations.AddField(
            model_name='metareq',
            name='dba_dev_dtm',
            field=models.TextField(blank=True, null=True, verbose_name='DBA 개발 승인 시간'),
        ),
        migrations.AddField(
            model_name='metareq',
            name='dba_prod_dtm',
            field=models.TextField(blank=True, null=True, verbose_name='DBA 운영 승인 시간'),
        ),
        migrations.AddField(
            model_name='metareq',
            name='pl_dev_dtm',
            field=models.TextField(blank=True, null=True, verbose_name='PL 개발 승인 시간'),
        ),
        migrations.AddField(
            model_name='metareq',
            name='pl_prod_dtm',
            field=models.TextField(blank=True, null=True, verbose_name='PL 운영 승인 시간'),
        ),
        migrations.AlterField(
            model_name='metareq',
            name='id_da_dev',
            field=models.ForeignKey(blank=True, db_column='id_da_dev', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='metareq_id_da_dev', to=settings.AUTH_USER_MODEL, verbose_name='개발_da_승인'),
        ),
        migrations.AlterField(
            model_name='metareq',
            name='id_dba_dev',
            field=models.ForeignKey(blank=True, db_column='id_dba_dev', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='metareq_id_dba_dev', to=settings.AUTH_USER_MODEL, verbose_name='개발_dba_승인'),
        ),
        migrations.AlterField(
            model_name='metareq',
            name='id_dba_prod',
            field=models.ForeignKey(blank=True, db_column='id_dba_prod', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='metareq_id_dba_prod', to=settings.AUTH_USER_MODEL, verbose_name='운영_dba_승인'),
        ),
        migrations.AlterField(
            model_name='metareq',
            name='id_pl_dev',
            field=models.ForeignKey(blank=True, db_column='id_pl_dev', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='metareq_id_pl_dev', to=settings.AUTH_USER_MODEL, verbose_name='개발_PL_승인'),
        ),
        migrations.AlterField(
            model_name='metareq',
            name='id_pl_prod',
            field=models.ForeignKey(blank=True, db_column='id_pl_prod', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='metareq_id_pl_prod', to=settings.AUTH_USER_MODEL, verbose_name='운영_PL_승인'),
        ),
    ]
