# Generated by Django 2.1.5 on 2020-04-18 22:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0158_auto_20200418_2207'),
    ]

    operations = [
        migrations.AddField(
            model_name='metareq',
            name='da_dev_comment',
            field=models.CharField(max_length=200, null=True, verbose_name='DA개발승인의견'),
        ),
        migrations.AddField(
            model_name='metareq',
            name='dba_dev_comment',
            field=models.CharField(max_length=200, null=True, verbose_name='DBA개발승인의견'),
        ),
        migrations.AddField(
            model_name='metareq',
            name='dba_prod_comment',
            field=models.CharField(max_length=200, null=True, verbose_name='DBA운영승인의견'),
        ),
        migrations.AddField(
            model_name='metareq',
            name='pl_dev_comment',
            field=models.CharField(max_length=200, null=True, verbose_name='PL개발승인의견'),
        ),
        migrations.AddField(
            model_name='metareq',
            name='pl_prod_comment',
            field=models.CharField(max_length=200, null=True, verbose_name='PL운영승인의견'),
        ),
        migrations.AlterField(
            model_name='metareq',
            name='da_dev_dtm',
            field=models.TextField(blank=True, null=True, verbose_name='DA개발승인시간'),
        ),
        migrations.AlterField(
            model_name='metareq',
            name='dba_dev_dtm',
            field=models.TextField(blank=True, null=True, verbose_name='DBA개발승인시간'),
        ),
        migrations.AlterField(
            model_name='metareq',
            name='dba_prod_dtm',
            field=models.TextField(blank=True, null=True, verbose_name='DBA운영승인시간'),
        ),
        migrations.AlterField(
            model_name='metareq',
            name='id_da_dev',
            field=models.ForeignKey(blank=True, db_column='id_da_dev', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='metareq_id_da_dev', to=settings.AUTH_USER_MODEL, verbose_name='DA개발승인자'),
        ),
        migrations.AlterField(
            model_name='metareq',
            name='id_dba_dev',
            field=models.ForeignKey(blank=True, db_column='id_dba_dev', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='metareq_id_dba_dev', to=settings.AUTH_USER_MODEL, verbose_name='DBA개발승인자'),
        ),
        migrations.AlterField(
            model_name='metareq',
            name='id_dba_prod',
            field=models.ForeignKey(blank=True, db_column='id_dba_prod', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='metareq_id_dba_prod', to=settings.AUTH_USER_MODEL, verbose_name='DBA운영승인자'),
        ),
        migrations.AlterField(
            model_name='metareq',
            name='id_pl_dev',
            field=models.ForeignKey(blank=True, db_column='id_pl_dev', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='metareq_id_pl_dev', to=settings.AUTH_USER_MODEL, verbose_name='PL개발승인자'),
        ),
        migrations.AlterField(
            model_name='metareq',
            name='id_pl_prod',
            field=models.ForeignKey(blank=True, db_column='id_pl_prod', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='metareq_id_pl_prod', to=settings.AUTH_USER_MODEL, verbose_name='PL운영승인자'),
        ),
        migrations.AlterField(
            model_name='metareq',
            name='pl_dev_dtm',
            field=models.TextField(blank=True, null=True, verbose_name='PL개발승인시간'),
        ),
        migrations.AlterField(
            model_name='metareq',
            name='pl_prod_dtm',
            field=models.TextField(blank=True, null=True, verbose_name='PL운영승인시간'),
        ),
    ]
