# Generated by Django 2.1.5 on 2020-04-19 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0159_auto_20200418_2212'),
    ]

    operations = [
        migrations.AlterField(
            model_name='metareq',
            name='da_dev_dtm',
            field=models.DateTimeField(blank=True, null=True, verbose_name='DA개발승인시간'),
        ),
        migrations.AlterField(
            model_name='metareq',
            name='dba_dev_dtm',
            field=models.DateTimeField(blank=True, null=True, verbose_name='DBA개발승인시간'),
        ),
        migrations.AlterField(
            model_name='metareq',
            name='dba_prod_dtm',
            field=models.DateTimeField(blank=True, null=True, verbose_name='DBA운영승인시간'),
        ),
        migrations.AlterField(
            model_name='metareq',
            name='pl_dev_dtm',
            field=models.DateTimeField(blank=True, null=True, verbose_name='PL개발승인시간'),
        ),
        migrations.AlterField(
            model_name='metareq',
            name='pl_prod_dtm',
            field=models.DateTimeField(blank=True, null=True, verbose_name='PL운영승인시간'),
        ),
    ]
