# Generated by Django 2.1.5 on 2020-04-19 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0161_auto_20200419_1013'),
    ]

    operations = [
        migrations.AlterField(
            model_name='metareq',
            name='da_dev_yn',
            field=models.CharField(blank=True, choices=[('0', '승인 전'), ('1', '승인'), ('2', '반려')], default=0, max_length=200, null=True, verbose_name='DA개발승인승인여부'),
        ),
        migrations.AlterField(
            model_name='metareq',
            name='dba_dev_yn',
            field=models.CharField(blank=True, choices=[('0', '승인 전'), ('1', '승인'), ('2', '반려')], default=0, max_length=200, null=True, verbose_name='DBA개발승인승인여부'),
        ),
        migrations.AlterField(
            model_name='metareq',
            name='dba_prod_yn',
            field=models.CharField(blank=True, choices=[('0', '승인 전'), ('1', '승인'), ('2', '반려')], default=0, max_length=200, null=True, verbose_name='DBA운영승인승인여부'),
        ),
        migrations.AlterField(
            model_name='metareq',
            name='pl_dev_yn',
            field=models.CharField(blank=True, choices=[('0', '승인 전'), ('1', '승인'), ('2', '반려')], default=0, max_length=200, null=True, verbose_name='PL개발승인승인여부'),
        ),
        migrations.AlterField(
            model_name='metareq',
            name='pl_prod_yn',
            field=models.CharField(blank=True, choices=[('0', '승인 전'), ('1', '승인'), ('2', '반려')], default=0, max_length=200, null=True, verbose_name='PL운영승인승인여부'),
        ),
    ]
