# Generated by Django 2.1.5 on 2020-04-21 11:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0163_auto_20200420_1049'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dbdetail',
            name='id_dblist',
            field=models.ForeignKey(blank=True, db_column='id_dblist', null=True, on_delete=django.db.models.deletion.CASCADE, to='database.DbList', verbose_name='DB명'),
        ),
        migrations.AlterField(
            model_name='metareq',
            name='obj_class',
            field=models.CharField(choices=[('1', 'TABLE(표준)'), ('2', 'TABLE(비표준)'), ('3', 'Package'), ('4', 'Procedure'), ('5', 'Function'), ('6', 'Sequence'), ('7', 'INDEX'), ('8', '권한'), ('9', '기타')], default='1', max_length=30, null=True, verbose_name='오브젝트 유형'),
        ),
        migrations.AlterField(
            model_name='userlist',
            name='id_user_name',
            field=models.ForeignKey(blank=True, db_column='id_user_name', null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='이름'),
        ),
    ]
