# Generated by Django 2.1.5 on 2020-04-21 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0164_auto_20200421_1143'),
    ]

    operations = [
        migrations.AddField(
            model_name='dblist',
            name='infra_op_yn',
            field=models.CharField(blank=True, choices=[('1', 'Y'), ('0', 'N')], default='1', max_length=30, null=True, verbose_name='인프라팀운영여부'),
        ),
    ]
