# Generated by Django 2.1.5 on 2020-04-21 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0167_metareqlist_data_default'),
    ]

    operations = [
        migrations.AddField(
            model_name='columnlist',
            name='not_null',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='NotNull여부'),
        ),
    ]
