# Generated by Django 2.1.5 on 2020-04-21 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0168_columnlist_not_null'),
    ]

    operations = [
        migrations.AlterField(
            model_name='columnlist',
            name='not_null',
            field=models.CharField(blank=True, choices=[('1', 'Y'), ('0', 'N')], default='0', max_length=30, verbose_name='NotNull여부'),
        ),
    ]
