# Generated by Django 2.1.5 on 2020-04-23 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0173_auto_20200423_1801'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tablelist',
            name='secu_yn',
            field=models.CharField(blank=True, choices=[('1', 'Y'), ('0', 'N')], default='0', max_length=30, null=True, verbose_name='개인정보여부'),
        ),
    ]
