# Generated by Django 2.1.5 on 2020-04-24 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0174_auto_20200423_1803'),
    ]

    operations = [
        migrations.AddField(
            model_name='metareq',
            name='script_dtm',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Script저장일시'),
        ),
        migrations.AlterField(
            model_name='metareq',
            name='obj_class',
            field=models.CharField(choices=[('1', 'TABLE(표준)'), ('2', 'TABLE(비표준)'), ('3', 'Package'), ('4', 'Procedure'), ('5', 'Function'), ('6', 'Sequence'), ('7', 'INDEX'), ('8', '권한'), ('9', '기타')], max_length=30, null=True, verbose_name='오브젝트 유형'),
        ),
        migrations.AlterField(
            model_name='metareq',
            name='obj_new',
            field=models.CharField(choices=[('1', '변경'), ('2', '신규'), ('3', '삭제')], max_length=30, null=True, verbose_name='변경 유형'),
        ),
    ]
