# Generated by Django 2.1.5 on 2020-04-24 12:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('database', '0175_auto_20200424_1233'),
    ]

    operations = [
        migrations.AddField(
            model_name='metareq',
            name='id_script_reg_user',
            field=models.ForeignKey(blank=True, db_column='id_script_reg_user', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='metareq_id_script_reg_user', to=settings.AUTH_USER_MODEL, verbose_name='Script등록자'),
        ),
    ]
