# Generated by Django 2.1.5 on 2020-04-28 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0176_metareq_id_script_reg_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='metareq',
            name='req_script',
            field=models.TextField(blank=True, null=True, verbose_name='개발자 요청 스크립트'),
        ),
        migrations.AlterField(
            model_name='metareq',
            name='script',
            field=models.TextField(blank=True, null=True, verbose_name='DBA Script'),
        ),
        migrations.AlterField(
            model_name='metareq',
            name='title',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='제목'),
        ),
    ]
