# Generated by Django 2.1.5 on 2020-04-28 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0177_auto_20200428_1008'),
    ]

    operations = [
        migrations.AlterField(
            model_name='metareq',
            name='da_dev_yn',
            field=models.CharField(choices=[('0', '승인 전'), ('1', '승인'), ('2', '반려')], default='0', max_length=200, verbose_name='DA개발승인승인여부'),
        ),
        migrations.AlterField(
            model_name='metareq',
            name='dba_dev_yn',
            field=models.CharField(choices=[('0', '승인 전'), ('1', '승인'), ('2', '반려')], default='0', max_length=200, verbose_name='DBA개발승인승인여부'),
        ),
        migrations.AlterField(
            model_name='metareq',
            name='dba_prod_yn',
            field=models.CharField(choices=[('0', '승인 전'), ('1', '승인'), ('2', '반려')], default='0', max_length=200, verbose_name='DBA운영승인승인여부'),
        ),
        migrations.AlterField(
            model_name='metareq',
            name='pl_dev_yn',
            field=models.CharField(choices=[('0', '승인 전'), ('1', '승인'), ('2', '반려')], default='0', max_length=200, verbose_name='PL개발승인승인여부'),
        ),
        migrations.AlterField(
            model_name='metareq',
            name='pl_prod_yn',
            field=models.CharField(choices=[('0', '승인 전'), ('1', '승인'), ('2', '반려')], default='0', max_length=200, verbose_name='PL운영승인승인여부'),
        ),
        migrations.AlterField(
            model_name='metareq',
            name='req_prod_yn',
            field=models.CharField(choices=[('0', '승인 전'), ('1', '승인'), ('2', '반려')], default='0', max_length=200, verbose_name='운영반영요청여부'),
        ),
    ]
