# Generated by Django 2.1.5 on 2020-04-28 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0178_auto_20200428_1045'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tablelist',
            name='lob_mb',
            field=models.BigIntegerField(blank=True, default=0, null=True, verbose_name='LOB사이즈(MB)'),
        ),
        migrations.AlterField(
            model_name='tablelist',
            name='total_mb',
            field=models.BigIntegerField(blank=True, default=0, null=True, verbose_name='사이즈(MB)'),
        ),
    ]
