# Generated by Django 2.1.5 on 2020-04-29 14:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0179_auto_20200428_1150'),
    ]

    operations = [
        migrations.AddField(
            model_name='userexecutesql',
            name='id_dbdetail',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='database.DbDetail', verbose_name='DB상세'),
        ),
    ]
