# Generated by Django 2.1.5 on 2020-05-08 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0180_userexecutesql_id_dbdetail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='metareq',
            name='obj_class',
            field=models.CharField(choices=[('1', 'TABLE(표준)'), ('2', 'TABLE(비표준)'), ('3', 'INDEX'), ('4', '권한'), ('5', 'PROCEDURE'), ('6', 'FUNCTION'), ('7', 'SEQUENCE'), ('8', 'PACKAGE'), ('9', '기타')], max_length=30, null=True, verbose_name='오브젝트 유형'),
        ),
        migrations.AlterField(
            model_name='tuninglist',
            name='bind_value',
            field=models.TextField(blank=True, help_text='SQL에 바인딩되는 값을 꼭 입력해주세요', null=True, verbose_name='바인딩값'),
        ),
        migrations.AlterField(
            model_name='tuninglist',
            name='sql_info',
            field=models.TextField(null=True, verbose_name='SQL 설명'),
        ),
        migrations.AlterField(
            model_name='tuninglist',
            name='tuning_info',
            field=models.TextField(blank=True, null=True, verbose_name='튜너의견(튜너 작성)'),
        ),
    ]
