# Generated by Django 2.1.5 on 2020-05-08 13:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('database', '0181_auto_20200508_1140'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reg_dtm', models.DateTimeField(auto_now_add=True, verbose_name='프로젝트 시작 일자')),
                ('title', models.CharField(max_length=100, verbose_name='프로젝트명')),
                ('id_reg_user', models.ForeignKey(blank=True, db_column='id_reg_user', null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='등록자')),
            ],
            options={
                'verbose_name': '[DBA-99] 프로젝트 리스트',
                'verbose_name_plural': '[DBA-99] 프로젝트 리스트',
                'db_table': 'cust_project_list',
            },
        ),
    ]
