# Generated by Django 2.1.5 on 2020-05-08 13:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0183_auto_20200508_1340'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='projectlist',
            name='start_dtm',
        ),
    ]
