# Generated by Django 2.1.5 on 2020-05-08 13:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0184_remove_projectlist_start_dtm'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='projectlist',
            name='id_reg_user',
        ),
        migrations.DeleteModel(
            name='ProjectList',
        ),
    ]
