# Generated by Django 2.1.5 on 2020-05-08 14:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0186_projectlist'),
    ]

    operations = [
        migrations.AddField(
            model_name='tuninglist',
            name='id_projectlist',
            field=models.ForeignKey(blank=True, db_column='id_projectlist', null=True, on_delete=django.db.models.deletion.CASCADE, to='database.ProjectList', verbose_name='프로젝트리스트'),
        ),
    ]
