# Generated by Django 2.1.5 on 2020-05-11 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0189_weekdba_dist_dtm'),
    ]

    operations = [
        migrations.AlterField(
            model_name='weekdba',
            name='dba',
            field=models.CharField(blank=True, choices=[('이치호', '이치호'), ('이정아', '이정아'), ('정관호', '정관호')], default='0', max_length=30, null=True, verbose_name='DBA'),
        ),
    ]
