# Generated by Django 2.1.5 on 2020-05-13 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0190_auto_20200511_1934'),
    ]

    operations = [
        migrations.AddField(
            model_name='metareq',
            name='csr',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='CSR'),
        ),
        migrations.AddField(
            model_name='metareq',
            name='dist_dtm',
            field=models.DateTimeField(blank=True, null=True, verbose_name='배포희망일자'),
        ),
        migrations.AlterField(
            model_name='weekdba',
            name='dba',
            field=models.CharField(blank=True, choices=[('이치호', '이치호'), ('이정아', '이정아'), ('정관호', '정관호')], max_length=30, null=True, verbose_name='DBA'),
        ),
    ]
