# Generated by Django 2.1.5 on 2020-05-13 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0191_auto_20200513_1851'),
    ]

    operations = [
        migrations.AlterField(
            model_name='metareq',
            name='dist_dtm',
            field=models.DateField(blank=True, null=True, verbose_name='배포희망일자'),
        ),
    ]
