# Generated by Django 2.1.5 on 2020-05-14 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0192_auto_20200513_1910'),
    ]

    operations = [
        migrations.AddField(
            model_name='dblist',
            name='metareq_yn',
            field=models.CharField(blank=True, choices=[('1', 'Y'), ('0', 'N')], default='0', max_length=30, null=True, verbose_name='DBA변경관리여부'),
        ),
    ]
