# Generated by Django 2.1.5 on 2020-05-20 10:17

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('database', '0195_userlist_drop_dtm'),
    ]

    operations = [
        migrations.CreateModel(
            name='MonitorItemList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_nm', models.CharField(help_text='"parameter 명 사용되며 알파벳+언더바만 사용 가능', max_length=100, validators=[django.core.validators.RegexValidator('^[a-zA-Z_]*$', '영문,언더바(_)만 입력 가능합니다.')], verbose_name='모니터링 항목')),
                ('use_yn', models.CharField(choices=[('1', 'Y'), ('0', 'N')], default='0', max_length=30, verbose_name='사용여부')),
                ('sql_text', models.TextField(blank=True, help_text='"SELECT 절에는 단일 항목, 하나의 ROW만 조회되도록 작성해주세요', null=True, verbose_name='모니터링 SQL')),
                ('reg_dtm', models.DateTimeField(auto_now_add=True, verbose_name='등록일자')),
                ('id_dbtype', models.ForeignKey(blank=True, db_column='id_dbtype', null=True, on_delete=django.db.models.deletion.PROTECT, to='database.DbType', verbose_name='DBMS종류')),
                ('id_reg_user', models.ForeignKey(blank=True, db_column='id_reg_user', null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='등록자')),
            ],
            options={
                'verbose_name': '모니터링아이템리스트',
                'verbose_name_plural': '모니터링아이템리스트',
                'db_table': 'cust_monitor_item_list',
            },
        ),
    ]
