# Generated by Django 2.1.5 on 2020-05-20 10:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0196_monitoritemlist'),
    ]

    operations = [
        migrations.CreateModel(
            name='MonitorItemLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('monitor_value', models.IntegerField(blank=True, default=100, null=True, verbose_name='값')),
                ('error_yn', models.CharField(choices=[('1', 'Y'), ('0', 'N')], default='0', max_length=30, verbose_name='에러여부')),
                ('error_msg', models.TextField(blank=True, null=True, verbose_name='에러메시지')),
                ('reg_dtm', models.DateTimeField(auto_now_add=True, verbose_name='등록일자')),
                ('id_dbtype', models.ForeignKey(blank=True, db_column='id_dbtype', null=True, on_delete=django.db.models.deletion.CASCADE, to='database.DbType', verbose_name='DBMS종류')),
            ],
            options={
                'verbose_name': '모니터링아이템로그',
                'verbose_name_plural': '모니터링아이템로그',
                'db_table': 'cust_monitor_item_log',
            },
        ),
        migrations.AlterField(
            model_name='monitoritemlist',
            name='id_dbtype',
            field=models.ForeignKey(blank=True, db_column='id_dbtype', null=True, on_delete=django.db.models.deletion.CASCADE, to='database.DbType', verbose_name='DBMS종류'),
        ),
        migrations.AlterField(
            model_name='monitoritemlist',
            name='id_reg_user',
            field=models.ForeignKey(blank=True, db_column='id_reg_user', null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='등록자'),
        ),
        migrations.AddField(
            model_name='monitoritemlog',
            name='id_monitoritemlist',
            field=models.ForeignKey(blank=True, db_column='id_monitoritemlist', null=True, on_delete=django.db.models.deletion.CASCADE, to='database.MonitorItemList', verbose_name='모니터링아이템리스트'),
        ),
        migrations.AddField(
            model_name='monitoritemlog',
            name='id_opercd',
            field=models.ForeignKey(blank=True, db_column='id_opercd', null=True, on_delete=django.db.models.deletion.CASCADE, to='database.OperCd', verbose_name='운영구분'),
        ),
    ]
