# Generated by Django 2.1.5 on 2020-05-20 11:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0197_auto_20200520_1043'),
    ]

    operations = [
        migrations.AddField(
            model_name='monitoritemlog',
            name='id_dblist',
            field=models.ForeignKey(blank=True, db_column='id_dblist', null=True, on_delete=django.db.models.deletion.CASCADE, to='database.DbList', verbose_name='DB명'),
        ),
    ]
