# Generated by Django 2.1.5 on 2020-05-20 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0198_monitoritemlog_id_dblist'),
    ]

    operations = [
        migrations.AddField(
            model_name='dblist',
            name='monitor_yn',
            field=models.CharField(blank=True, choices=[('1', 'Y'), ('0', 'N')], default='0', max_length=30, null=True, verbose_name='모니터링여부'),
        ),
    ]
