# Generated by Django 2.1.5 on 2020-05-26 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0199_dblist_monitor_yn'),
    ]

    operations = [
        migrations.AlterField(
            model_name='monitoritemlog',
            name='monitor_value',
            field=models.CharField(blank=True, max_length=300, null=True, verbose_name='값'),
        ),
    ]
