# Generated by Django 2.1.5 on 2020-05-26 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0200_auto_20200526_1427'),
    ]

    operations = [
        migrations.AddField(
            model_name='monitoritemlist',
            name='risk_level',
            field=models.CharField(choices=[('0', '주의'), ('1', '심각'), ('2', '장애')], default='0', max_length=30, verbose_name='리스크레벨'),
        ),
    ]
