# Generated by Django 2.1.5 on 2020-05-26 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0201_monitoritemlist_risk_level'),
    ]

    operations = [
        migrations.AddField(
            model_name='monitoritemlist',
            name='limit_value',
            field=models.IntegerField(blank=True, default='10', null=True, verbose_name='임계치'),
        ),
    ]
