# Generated by Django 2.1.5 on 2020-05-26 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0202_monitoritemlist_limit_value'),
    ]

    operations = [
        migrations.AddField(
            model_name='dbdetail',
            name='active_yn',
            field=models.CharField(blank=True, choices=[('1', 'Y'), ('0', 'N')], default='1', max_length=30, null=True, verbose_name='Acitve여부'),
        ),
    ]
