# Generated by Django 2.1.5 on 2020-05-26 15:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0203_dbdetail_active_yn'),
    ]

    operations = [
        migrations.AddField(
            model_name='monitoritemlog',
            name='id_dbdetail',
            field=models.ForeignKey(blank=True, db_column='id_dbdetail', null=True, on_delete=django.db.models.deletion.CASCADE, to='database.DbDetail', verbose_name='DB상세'),
        ),
        migrations.AlterField(
            model_name='dbdetail',
            name='active_yn',
            field=models.CharField(blank=True, choices=[('1', 'Y'), ('0', 'N')], default='1', max_length=30, null=True, verbose_name='Open여부'),
        ),
    ]
