# Generated by Django 2.1.5 on 2020-05-27 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0204_auto_20200526_1528'),
    ]

    operations = [
        migrations.AddField(
            model_name='dblist',
            name='emp_privacy_yn',
            field=models.CharField(blank=True, choices=[('1', 'Y'), ('0', 'N')], default='0', max_length=30, null=True, verbose_name='임직원 개인정보 보유 여부'),
        ),
        migrations.AlterField(
            model_name='dblist',
            name='privacy_yn',
            field=models.CharField(blank=True, choices=[('1', 'Y'), ('0', 'N')], default='0', max_length=30, null=True, verbose_name='고객 개인정보 보유 여부'),
        ),
    ]
