# Generated by Django 2.1.5 on 2020-05-29 09:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('database', '0209_auto_20200529_0950'),
    ]

    operations = [
        migrations.CreateModel(
            name='DBDetailMonitorItemList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('limit_value', models.IntegerField(blank=True, default='0', null=True, verbose_name='임계치')),
                ('risk_level', models.CharField(choices=[('0', '주의'), ('1', '심각'), ('2', '장애')], default='0', max_length=30, verbose_name='리스크레벨')),
                ('reg_dtm', models.DateTimeField(auto_now_add=True, null=True, verbose_name='등록일자')),
                ('id_dbdetail', models.ForeignKey(db_column='id_dbdetail', on_delete=django.db.models.deletion.CASCADE, to='database.DbDetail', verbose_name='DB상세')),
                ('id_monitoritemlist', models.ForeignKey(db_column='id_monitoritemlist', on_delete=django.db.models.deletion.CASCADE, to='database.MonitorItemList', verbose_name='모니터아이템리스트')),
                ('id_reg_user', models.ForeignKey(blank=True, db_column='id_reg_user', null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='등록자')),
            ],
            options={
                'verbose_name': 'DB - 모니터링ITEM 매핑',
                'verbose_name_plural': 'DB - 모니터링ITEM 매핑',
                'db_table': 'cust_dbdetail_monitoritemlist',
            },
        ),
        migrations.AddField(
            model_name='dbdetail',
            name='id_monitoritemlist',
            field=models.ManyToManyField(blank=True, through='database.DBDetailMonitorItemList', to='database.MonitorItemList', verbose_name='모니터링 리스트'),
        ),
    ]
