# Generated by Django 2.1.5 on 2020-05-30 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0212_remove_monitoritemlog_monitor_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='monitoritemlog',
            name='monitor_key',
            field=models.CharField(blank=True, max_length=300, null=True, verbose_name='제목(key)'),
        ),
    ]
