# Generated by Django 2.1.5 on 2020-05-30 22:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0214_auto_20200530_2235'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='monitoritemlog',
            name='monitor_key',
        ),
    ]
