# Generated by Django 2.1.5 on 2020-06-01 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0218_auto_20200530_2254'),
    ]

    operations = [
        migrations.AddField(
            model_name='monitoritemlog',
            name='curr_yn',
            field=models.CharField(choices=[('1', 'Y'), ('0', 'N')], default='0', max_length=30, verbose_name='현재여부'),
        ),
    ]
