# Generated by Django 3.0.6 on 2020-06-03 09:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0219_monitoritemlog_curr_yn'),
    ]

    operations = [
        migrations.CreateModel(
            name='MonitorTablespaceLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tablespace_name', models.CharField(default='', max_length=100, verbose_name='테이블스페이스명')),
                ('free', models.CharField(blank=True, max_length=100, null=True, verbose_name='FREE사이즈')),
                ('used', models.CharField(blank=True, max_length=100, null=True, verbose_name='사용사이즈')),
                ('usage', models.CharField(blank=True, max_length=100, null=True, verbose_name='사용율')),
                ('reg_dtm', models.DateTimeField(auto_now_add=True, verbose_name='등록일자')),
                ('curr_yn', models.CharField(choices=[('1', 'Y'), ('0', 'N')], default='0', max_length=30, verbose_name='현재여부')),
                ('id_dbdetail', models.ForeignKey(blank=True, db_column='id_dbdetail', null=True, on_delete=django.db.models.deletion.CASCADE, to='database.DbDetail', verbose_name='DB상세')),
            ],
            options={
                'verbose_name': '모니터링테이블스페이스로그',
                'verbose_name_plural': '모니터링테이블스페이스로그',
                'db_table': 'cust_monitor_tablespace_log',
            },
        ),
        migrations.CreateModel(
            name='MonitorTablespace',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tablespace_name', models.CharField(default='', max_length=100, verbose_name='테이블스페이스명')),
                ('limit_value', models.IntegerField(blank=True, default='90', null=True, verbose_name='임계치(%)')),
                ('id_dbdetail', models.ForeignKey(blank=True, db_column='id_dbdetail', null=True, on_delete=django.db.models.deletion.CASCADE, to='database.DbDetail', verbose_name='DB상세')),
            ],
            options={
                'verbose_name': '모니터링테이블스페이스',
                'verbose_name_plural': '모니터링테이블스페이스',
                'db_table': 'cust_monitor_tablespace',
            },
        ),
    ]
