# Generated by Django 3.0.6 on 2020-06-03 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0222_monitortablespacelog_total'),
    ]

    operations = [
        migrations.AlterField(
            model_name='monitortablespace',
            name='limit_value',
            field=models.IntegerField(blank=True, default='95', null=True, verbose_name='임계치(%)'),
        ),
    ]
