# Generated by Django 3.0.6 on 2020-06-03 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0223_auto_20200603_1048'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='monitoritemlist',
            options={'verbose_name': '모니터링 - 아이템리스트', 'verbose_name_plural': '모니터링 - 아이템리스트'},
        ),
        migrations.AlterModelOptions(
            name='monitoritemlog',
            options={'verbose_name': '모니터링 - 아이템로그', 'verbose_name_plural': '모니터링 - 아이템로그'},
        ),
        migrations.AlterModelOptions(
            name='monitortablespace',
            options={'verbose_name': '모니터링 - 테이블스페이스', 'verbose_name_plural': '모니터링 - 테이블스페이스'},
        ),
        migrations.AddField(
            model_name='monitortablespace',
            name='explain',
            field=models.TextField(null=True, verbose_name='비고'),
        ),
    ]
