# Generated by Django 3.0.6 on 2020-06-03 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0226_auto_20200603_1259'),
    ]

    operations = [
        migrations.AddField(
            model_name='dbdetail',
            name='slave_yn',
            field=models.CharField(blank=True, choices=[('1', 'Y'), ('0', 'N')], default='0', max_length=30, null=True, verbose_name='Slave여부'),
        ),
    ]
