# Generated by Django 3.0.6 on 2020-06-03 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0228_auto_20200603_1749'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dbdetail',
            name='ha_case',
            field=models.CharField(blank=True, choices=[('0', ''), ('1', 'Slave'), ('2', 'DRBD')], default='0', max_length=30, null=True, verbose_name='HA유형'),
        ),
    ]
