# Generated by Django 3.0.6 on 2020-06-04 16:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('database', '0229_auto_20200603_1750'),
    ]

    operations = [
        migrations.CreateModel(
            name='HaCase',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ha_case', models.CharField(blank=True, max_length=100, null=True, verbose_name='HA유형')),
                ('reg_dtm', models.DateTimeField(auto_now_add=True, null=True, verbose_name='등록일자')),
                ('id_reg_user', models.ForeignKey(blank=True, db_column='id_reg_user', null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='등록자')),
            ],
            options={
                'verbose_name': 'HA 유형',
                'verbose_name_plural': 'HA 유형',
                'db_table': 'cust_ha_case',
            },
        ),
    ]
