# Generated by Django 3.0.6 on 2020-06-04 16:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0230_hacase'),
    ]

    operations = [
        migrations.AddField(
            model_name='dbdetail',
            name='id_hacase',
            field=models.ForeignKey(blank=True, db_column='id_hacase', null=True, on_delete=django.db.models.deletion.PROTECT, to='database.HaCase', verbose_name='HA구분'),
        ),
    ]
