# Generated by Django 3.0.6 on 2020-06-04 16:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0231_dbdetail_id_hacase'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dbdetail',
            name='ha_case',
        ),
    ]
