# Generated by Django 3.0.6 on 2020-06-05 10:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('database', '0232_remove_dbdetail_ha_case'),
    ]

    operations = [
        migrations.CreateModel(
            name='StdAttr',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('std_attr_kor', models.CharField(blank=True, max_length=100, null=True, verbose_name='한글용어명')),
                ('std_attr_eng', models.CharField(blank=True, max_length=100, null=True, verbose_name='영문용어명')),
                ('data_type', models.CharField(blank=True, max_length=100, null=True, verbose_name='DataType')),
                ('reg_dtm', models.DateTimeField(auto_now_add=True, null=True, verbose_name='등록일자')),
                ('expl', models.TextField(blank=True, null=True, verbose_name='설명')),
                ('id_dblist', models.ForeignKey(blank=True, db_column='id_dblist', null=True, on_delete=django.db.models.deletion.CASCADE, to='database.DbList', verbose_name='DB명')),
                ('id_reg_user', models.ForeignKey(blank=True, db_column='id_reg_user', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL, verbose_name='등록자')),
            ],
            options={
                'verbose_name': '표준용어',
                'verbose_name_plural': '표준용어',
                'db_table': 'cust_std_attr',
            },
        ),
    ]
