# Generated by Django 3.0.6 on 2020-06-05 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0233_stdattr'),
    ]

    operations = [
        migrations.AddField(
            model_name='monitoritemlist',
            name='sms_message',
            field=models.CharField(blank=True, max_length=300, null=True, verbose_name='알람 메시지'),
        ),
    ]
