# Generated by Django 3.0.6 on 2020-06-05 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0234_monitoritemlist_sms_message'),
    ]

    operations = [
        migrations.AddField(
            model_name='dbdetailmonitoritemlist',
            name='compare_case',
            field=models.CharField(choices=[('0', '='), ('1', '<'), ('2', '>')], default='0', max_length=30, verbose_name='정상조건'),
        ),
        migrations.AddField(
            model_name='monitoritemlist',
            name='compare_case',
            field=models.CharField(choices=[('0', '='), ('1', '<'), ('2', '>')], default='0', max_length=30, verbose_name='정상조건'),
        ),
        migrations.AlterField(
            model_name='monitoritemlist',
            name='limit_value',
            field=models.IntegerField(blank=True, default='10', null=True, verbose_name='Default 임계치'),
        ),
        migrations.AlterField(
            model_name='monitoritemlist',
            name='risk_level',
            field=models.CharField(choices=[('0', '주의'), ('1', '심각'), ('2', '장애')], default='0', max_length=30, verbose_name='Default 리스크레벨'),
        ),
    ]
