# Generated by Django 3.0.6 on 2020-06-05 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0235_auto_20200605_1533'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dbdetailmonitoritemlist',
            name='compare_case',
            field=models.CharField(choices=[('0', '='), ('1', '<'), ('2', '>')], default='0', max_length=30, verbose_name='정상조건(오른쪽 임계치 보다 < 작으면 정상'),
        ),
        migrations.AlterField(
            model_name='dbdetailmonitoritemlist',
            name='limit_value',
            field=models.CharField(blank=True, default='0', max_length=100, null=True, verbose_name='임계치'),
        ),
        migrations.AlterField(
            model_name='monitoritemlist',
            name='limit_value',
            field=models.CharField(blank=True, default='10', max_length=100, null=True, verbose_name='Default임계치'),
        ),
    ]
