# Generated by Django 3.0.6 on 2020-06-05 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0236_auto_20200605_1536'),
    ]

    operations = [
        migrations.AlterField(
            model_name='monitoritemlist',
            name='compare_case',
            field=models.CharField(choices=[('0', '='), ('1', '<'), ('2', '>')], default='0', max_length=30, verbose_name='default 정상조건(오른쪽 임계치 보다 < 작으면 정상'),
        ),
    ]
