# Generated by Django 3.0.6 on 2020-06-05 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0237_auto_20200605_1542'),
    ]

    operations = [
        migrations.AddField(
            model_name='monitoritemlist',
            name='column_name',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='SQL내 모니터링 컬럼'),
        ),
    ]
