# Generated by Django 3.0.6 on 2020-06-05 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0238_monitoritemlist_column_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='monitoritemlist',
            name='graph_yn',
            field=models.CharField(choices=[('1', 'Y'), ('0', 'N')], default='0', max_length=30, verbose_name='그래프표현여부'),
        ),
    ]
