# Generated by Django 3.0.6 on 2020-06-08 11:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0239_monitoritemlist_graph_yn'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stdattr',
            name='data_type',
        ),
        migrations.AddField(
            model_name='stdattr',
            name='id_domain',
            field=models.ForeignKey(blank=True, db_column='id_domain', null=True, on_delete=django.db.models.deletion.PROTECT, to='database.Domain', verbose_name='도메인명'),
        ),
        migrations.AlterField(
            model_name='monitoritemlist',
            name='item_nm',
            field=models.CharField(max_length=100, verbose_name='상위 모니터링 항목'),
        ),
    ]
