# Generated by Django 3.0.6 on 2020-06-08 11:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0240_auto_20200608_1106'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stdattr',
            name='id_dblist',
            field=models.ForeignKey(blank=True, db_column='id_dblist', null=True, on_delete=django.db.models.deletion.PROTECT, to='database.DbList', verbose_name='DB명'),
        ),
    ]
