# Generated by Django 3.0.6 on 2020-06-08 11:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0241_auto_20200608_1107'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stdattr',
            name='id_domain',
        ),
        migrations.AddField(
            model_name='stdattr',
            name='id_stddomain',
            field=models.ForeignKey(blank=True, db_column='id_stddomain', null=True, on_delete=django.db.models.deletion.PROTECT, to='database.StdDomain', verbose_name='표준도메인'),
        ),
    ]
