# Generated by Django 3.0.6 on 2020-06-09 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0244_remove_stdattr_id_dblist'),
    ]

    operations = [
        migrations.AddField(
            model_name='stdword',
            name='accept_yn',
            field=models.CharField(blank=True, choices=[('1', 'Y'), ('0', 'N')], default='0', max_length=30, null=True, verbose_name='승인여부'),
        ),
    ]
