# Generated by Django 3.0.6 on 2020-06-09 10:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('database', '0245_stdword_accept_yn'),
    ]

    operations = [
        migrations.AddField(
            model_name='stdword',
            name='id_reg_user',
            field=models.ForeignKey(blank=True, db_column='id_reg_user', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL, verbose_name='등록자'),
        ),
        migrations.AddField(
            model_name='stdword',
            name='reg_dtm',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='등록일자'),
        ),
    ]
