# Generated by Django 3.0.6 on 2020-06-09 12:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('database', '0246_auto_20200609_1022'),
    ]

    operations = [
        migrations.AddField(
            model_name='stddomain',
            name='accept_yn',
            field=models.CharField(blank=True, choices=[('1', 'Y'), ('0', 'N')], default='0', max_length=30, null=True, verbose_name='승인여부'),
        ),
        migrations.AddField(
            model_name='stddomain',
            name='id_reg_user',
            field=models.ForeignKey(blank=True, db_column='id_reg_user', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL, verbose_name='등록자'),
        ),
        migrations.AddField(
            model_name='stddomain',
            name='reg_dtm',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='등록일자'),
        ),
    ]
