# Generated by Django 3.0.6 on 2020-06-15 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0247_auto_20200609_1251'),
    ]

    operations = [
        migrations.AddField(
            model_name='stdattr',
            name='reject_exp',
            field=models.TextField(blank=True, null=True, verbose_name='반려사유'),
        ),
        migrations.AddField(
            model_name='stddomain',
            name='reject_exp',
            field=models.TextField(blank=True, null=True, verbose_name='반려사유'),
        ),
        migrations.AddField(
            model_name='stdword',
            name='reject_exp',
            field=models.TextField(blank=True, null=True, verbose_name='반려사유'),
        ),
        migrations.AlterField(
            model_name='metareq',
            name='dba_dev_yn',
            field=models.CharField(choices=[('0', '승인 전'), ('1', '승인'), ('2', '반려')], default='0', max_length=200, verbose_name='DBA개발승인여부'),
        ),
        migrations.AlterField(
            model_name='metareq',
            name='dba_prod_yn',
            field=models.CharField(choices=[('0', '승인 전'), ('1', '승인'), ('2', '반려')], default='0', max_length=200, verbose_name='DBA운영승인여부'),
        ),
        migrations.AlterField(
            model_name='metareq',
            name='obj_class',
            field=models.CharField(choices=[('', '오브젝트 유형 선택'), ('2', 'TABLE'), ('3', 'INDEX'), ('4', '권한'), ('5', 'PROCEDURE'), ('6', 'FUNCTION'), ('7', 'SEQUENCE'), ('8', 'PACKAGE'), ('9', '기타')], max_length=30, null=True, verbose_name='오브젝트 유형'),
        ),
        migrations.AlterField(
            model_name='metareq',
            name='pl_dev_yn',
            field=models.CharField(choices=[('0', '승인 전'), ('1', '승인'), ('2', '반려')], default='0', max_length=200, verbose_name='PL개발승인여부'),
        ),
        migrations.AlterField(
            model_name='metareq',
            name='pl_prod_yn',
            field=models.CharField(choices=[('0', '승인 전'), ('1', '승인'), ('2', '반려')], default='0', max_length=200, verbose_name='PL운영승인여부'),
        ),
        migrations.AlterField(
            model_name='monitortablespace',
            name='explain',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='비고'),
        ),
        migrations.AlterField(
            model_name='stdattr',
            name='accept_yn',
            field=models.CharField(blank=True, choices=[('1', 'Y'), ('0', 'N'), ('2', '반려')], default='0', max_length=30, null=True, verbose_name='승인여부'),
        ),
        migrations.AlterField(
            model_name='stddomain',
            name='accept_yn',
            field=models.CharField(blank=True, choices=[('1', 'Y'), ('0', 'N'), ('2', '반려')], default='0', max_length=30, null=True, verbose_name='승인여부'),
        ),
        migrations.AlterField(
            model_name='stdword',
            name='accept_yn',
            field=models.CharField(blank=True, choices=[('1', 'Y'), ('0', 'N'), ('2', '반려')], default='0', max_length=30, null=True, verbose_name='승인여부'),
        ),
    ]
