# Generated by Django 3.0.6 on 2020-06-22 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0248_auto_20200615_1126'),
    ]

    operations = [
        migrations.AddField(
            model_name='dbdetail',
            name='monitor_yn',
            field=models.CharField(blank=True, choices=[('1', 'Y'), ('0', 'N')], default='0', max_length=30, null=True, verbose_name='모니터링여부'),
        ),
        migrations.AlterField(
            model_name='metareqlist',
            name='privacy_list',
            field=models.CharField(blank=True, choices=[('0', ''), ('1', '개인정보')], default='0', max_length=30, null=True, verbose_name='개인정보'),
        ),
        migrations.AlterField(
            model_name='stdattr',
            name='accept_yn',
            field=models.CharField(blank=True, choices=[('1', '대기중'), ('0', '승인'), ('2', '반려')], default='0', max_length=30, null=True, verbose_name='승인여부'),
        ),
        migrations.AlterField(
            model_name='stddomain',
            name='accept_yn',
            field=models.CharField(blank=True, choices=[('1', '대기중'), ('0', '승인'), ('2', '반려')], default='0', max_length=30, null=True, verbose_name='승인여부'),
        ),
        migrations.AlterField(
            model_name='stdword',
            name='accept_yn',
            field=models.CharField(blank=True, choices=[('1', '대기중'), ('0', '승인'), ('2', '반려')], default='0', max_length=30, null=True, verbose_name='승인여부'),
        ),
    ]
