# Generated by Django 3.0.6 on 2020-06-22 09:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0249_auto_20200622_0851'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dblist',
            name='monitor_yn',
        ),
    ]
