# Generated by Django 3.0.6 on 2020-06-23 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0250_remove_dblist_monitor_yn'),
    ]

    operations = [
        migrations.AlterField(
            model_name='metareq',
            name='dist_dtm',
            field=models.DateTimeField(blank=True, null=True, verbose_name='배포희망일자'),
        ),
    ]
