# Generated by Django 3.0.6 on 2020-06-23 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0251_auto_20200623_0859'),
    ]

    operations = [
        migrations.AlterField(
            model_name='weekdba',
            name='dist_dtm',
            field=models.DateTimeField(blank=True, null=True, verbose_name='정기반영일자'),
        ),
    ]
