# Generated by Django 3.0.6 on 2020-06-25 20:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0252_auto_20200623_0900'),
    ]

    operations = [
        migrations.AddField(
            model_name='batchlist',
            name='batch_time',
            field=models.CharField(choices=[('0', '9시 12시 18시'), ('1', '매시 정각')], default='0', max_length=30, verbose_name='배치시간'),
        ),
    ]
