# Generated by Django 3.0.6 on 2020-06-25 21:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0253_batchlist_batch_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='batchlist',
            name='batch_time',
        ),
    ]
