# Generated by Django 3.0.6 on 2020-07-02 21:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0254_remove_batchlist_batch_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='weekdba',
            name='freezing',
            field=models.CharField(blank=True, choices=[('1', 'Y'), ('0', 'N')], default='0', max_length=30, null=True, verbose_name='프리징여부'),
        ),
        migrations.AlterField(
            model_name='weekdba',
            name='dba',
            field=models.CharField(blank=True, choices=[('이치호,01075722752', '이치호,01075722752'), ('이정아,01071191554', '이정아,01071191554'), ('정관호,01062021633', '정관호,01062021633')], max_length=30, null=True, verbose_name='DBA'),
        ),
    ]
