# Generated by Django 3.0.6 on 2020-07-02 21:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0255_auto_20200702_2126'),
    ]

    operations = [
        migrations.AddField(
            model_name='metareq',
            name='check_prod_exec_yn',
            field=models.CharField(choices=[('1', '정기반영 대상'), ('0', '대상 아님')], default='0', max_length=200, verbose_name='금주 정기 반영 대상 여부'),
        ),
        migrations.AlterField(
            model_name='weekdba',
            name='freezing',
            field=models.CharField(blank=True, choices=[('1', 'Freezing'), ('0', '운영 반영 신청가능')], default='0', max_length=30, null=True, verbose_name='변경 관리 프리징 여부'),
        ),
    ]
