# Generated by Django 3.0.6 on 2020-07-02 22:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('database', '0256_auto_20200702_2154'),
    ]

    operations = [
        migrations.AlterField(
            model_name='metareq',
            name='id_reg_user',
            field=models.ForeignKey(blank=True, db_column='id_reg_user', null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='요청자'),
        ),
        migrations.AlterField(
            model_name='metareqlist',
            name='id_metareq',
            field=models.ForeignKey(blank=True, db_column='id_metareq', max_length=100, null=True, on_delete=django.db.models.deletion.CASCADE, to='database.MetaReq', verbose_name='메타요청'),
        ),
    ]
