# Generated by Django 3.0.6 on 2020-07-03 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0257_auto_20200702_2220'),
    ]

    operations = [
        migrations.AddField(
            model_name='dbdetail',
            name='conct_succs_yn',
            field=models.CharField(blank=True, choices=[('1', 'Y'), ('0', 'N')], default='0', max_length=30, null=True, verbose_name='접속성공여부'),
        ),
    ]
