# Generated by Django 3.0.6 on 2020-07-03 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0260_auto_20200703_1516'),
    ]

    operations = [
        migrations.AddField(
            model_name='stddomain',
            name='mysql_datatype',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='MYSQL데이터타입'),
        ),
        migrations.AddField(
            model_name='stddomain',
            name='oracle_datatype',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='ORACLE데이터타입'),
        ),
    ]
