# Generated by Django 3.0.6 on 2020-07-04 05:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0261_auto_20200703_1609'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stddomain',
            name='mysql_data_type',
        ),
        migrations.RemoveField(
            model_name='stddomain',
            name='mysql_decimal_leng',
        ),
        migrations.RemoveField(
            model_name='stddomain',
            name='mysql_leng',
        ),
        migrations.RemoveField(
            model_name='stddomain',
            name='oracle_data_type',
        ),
        migrations.RemoveField(
            model_name='stddomain',
            name='oracle_decimal_leng',
        ),
        migrations.RemoveField(
            model_name='stddomain',
            name='oracle_leng',
        ),
    ]
