# Generated by Django 3.0.6 on 2020-07-07 15:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0262_auto_20200704_0520'),
    ]

    operations = [
        migrations.CreateModel(
            name='MetaReqWeekDay',
            fields=[
            ],
            options={
                'verbose_name': '메타변경요청 - 정기반영',
                'verbose_name_plural': '메타변경요청 - 정기반영',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('database.metareq',),
        ),
        migrations.AlterModelOptions(
            name='stddomain',
            options={'ordering': ['info_type'], 'verbose_name': '표준도메인', 'verbose_name_plural': '표준도메인'},
        ),
        migrations.AddField(
            model_name='dbdetail',
            name='alert_yn',
            field=models.CharField(blank=True, choices=[('1', 'Y'), ('0', 'N')], default='0', max_length=30, null=True, verbose_name='Alert여부'),
        ),
        migrations.AlterField(
            model_name='metareq',
            name='da_dev_yn',
            field=models.CharField(choices=[('0', '승인 전'), ('1', '승인(반영)'), ('2', '반려')], default='0', max_length=200, verbose_name='DA개발승인승인여부'),
        ),
        migrations.AlterField(
            model_name='metareq',
            name='dba_dev_yn',
            field=models.CharField(choices=[('0', '승인 전'), ('1', '승인(반영)'), ('2', '반려')], default='0', max_length=200, verbose_name='DBA개발승인여부'),
        ),
        migrations.AlterField(
            model_name='metareq',
            name='dba_prod_yn',
            field=models.CharField(choices=[('0', '승인 전'), ('1', '승인(반영)'), ('2', '반려')], default='0', max_length=200, verbose_name='DBA 운영 반영 여부'),
        ),
        migrations.AlterField(
            model_name='metareq',
            name='pl_dev_yn',
            field=models.CharField(choices=[('0', '승인 전'), ('1', '승인(반영)'), ('2', '반려')], default='0', max_length=200, verbose_name='PL개발승인여부'),
        ),
        migrations.AlterField(
            model_name='metareq',
            name='pl_prod_yn',
            field=models.CharField(choices=[('0', '승인 전'), ('1', '승인(반영)'), ('2', '반려')], default='0', max_length=200, verbose_name='PL운영승인여부'),
        ),
        migrations.AlterField(
            model_name='metareq',
            name='req_prod_yn',
            field=models.CharField(choices=[('0', '승인 전'), ('1', '승인(반영)'), ('2', '반려')], default='0', max_length=200, verbose_name='운영반영요청여부'),
        ),
        migrations.AlterField(
            model_name='metareqlist',
            name='not_null',
            field=models.CharField(blank=True, choices=[('1', 'Y'), ('0', 'N')], default='0', max_length=30, null=True, verbose_name='NOT NULL'),
        ),
        migrations.AlterField(
            model_name='stdattr',
            name='id_stddomain',
            field=models.ForeignKey(blank=True, db_column='id_stddomain', null=True, on_delete=django.db.models.deletion.CASCADE, to='database.StdDomain', verbose_name='표준도메인'),
        ),
    ]
