# Generated by Django 3.0.6 on 2020-07-17 23:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0263_auto_20200707_1533'),
    ]

    operations = [
        migrations.AddField(
            model_name='monitoritemlog',
            name='elpased_time',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='수행시간'),
        ),
        migrations.AlterField(
            model_name='tablelist',
            name='secu_yn',
            field=models.CharField(blank=True, choices=[('1', 'Y'), ('0', 'N')], default='0', help_text='컬럼 중 하나라도 개인정보 컬럼이면 "Y" 체크해주세요.', max_length=30, null=True, verbose_name='개인정보여부'),
        ),
        migrations.AlterField(
            model_name='weekdba',
            name='dba',
            field=models.CharField(blank=True, choices=[('22980', '이치호'), ('22764', '이정아'), ('22916', '정관호')], max_length=30, null=True, verbose_name='DBA'),
        ),
    ]
