# Generated by Django 3.0.6 on 2020-07-18 00:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0264_auto_20200717_2359'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='monitoritemlog',
            name='elpased_time',
        ),
    ]
