# Generated by Django 3.0.6 on 2020-07-18 00:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0265_remove_monitoritemlog_elpased_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='monitoritemlog',
            name='elapsed_time',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='수행시간'),
        ),
    ]
