# Generated by Django 3.0.6 on 2020-07-29 00:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('database', '0269_auto_20200727_1028'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tablelist',
            options={'verbose_name': 'Table 리스트 ( 개인정보 컬럼 마킹 )', 'verbose_name_plural': 'Table 리스트 ( 개인정보 컬럼 마킹 )'},
        ),
        migrations.AlterField(
            model_name='columnlist',
            name='secu_yn',
            field=models.CharField(blank=True, choices=[('1', 'Y'), ('0', 'N')], max_length=30, null=True, verbose_name='컬럼 레벨 개인정보여부'),
        ),
        migrations.AlterField(
            model_name='tablelist',
            name='secu_yn',
            field=models.CharField(blank=True, choices=[('1', 'Y'), ('0', 'N')], default='0', help_text='컬럼 중 하나라도 개인정보 컬럼이면 "Y" 체크해주세요.', max_length=30, null=True, verbose_name='테이블 레벨 개인정보여부'),
        ),
        migrations.CreateModel(
            name='SendEmailTargetList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('send_case', models.CharField(blank=True, choices=[('1', '정기반영 - 일반'), ('2', '정기반영 - 개인정보 포함')], default='1', max_length=30, null=True, verbose_name='발송유형')),
                ('reg_dtm', models.DateTimeField(auto_now_add=True, null=True, verbose_name='등록일자')),
                ('id_receive_user', models.ForeignKey(blank=True, db_column='id_receive_user', null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='수인인')),
            ],
            options={
                'verbose_name': '이메일수신리스트',
                'verbose_name_plural': '이메일수신리스트',
                'db_table': 'cust_email_target_list',
            },
        ),
    ]
