# Generated by Django 3.0.6 on 2020-07-31 11:31

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('database', '0270_auto_20200729_0017'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='weekdba',
            name='freezing',
        ),
        migrations.AddField(
            model_name='dbdetail',
            name='id_sms_receive_user',
            field=models.ManyToManyField(blank=True, db_table='cust_monitor_sms_receive_user', help_text='모니터링 알람을 받는 유저입니다.', max_length=300, related_name='cust_monitor_sms_receive_user', to=settings.AUTH_USER_MODEL, verbose_name='모니터링 SMS 수신 인원(복수 선택 가능)'),
        ),
    ]
