# Generated by Django 3.0.6 on 2020-08-07 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0272_auto_20200807_0853'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stdattr',
            name='accept_yn',
            field=models.IntegerField(blank=True, choices=[(1, '대기중'), (0, '승인'), (2, '반려')], default='0', null=True, verbose_name='승인여부'),
        ),
    ]
