# Generated by Django 3.0.6 on 2020-08-07 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0273_auto_20200807_1159'),
    ]

    operations = [
        migrations.AddField(
            model_name='stdattr',
            name='csr_no',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='CSR번호'),
        ),
    ]
