# Generated by Django 3.0.6 on 2020-08-12 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0274_stdattr_csr_no'),
    ]

    operations = [
        migrations.AddField(
            model_name='stddomain',
            name='group_code',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='값(그룹코드 or 테이블영문명)'),
        ),
        migrations.AddField(
            model_name='stddomain',
            name='group_code_yn',
            field=models.CharField(blank=True, choices=[('0', '그룹코드(공통코드테이블)'), ('1', '개별코드(별도테이블)')], default='0', max_length=30, null=True, verbose_name='코드유형'),
        ),
    ]
