# Generated by Django 3.0.6 on 2020-08-18 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0275_auto_20200812_1002'),
    ]

    operations = [
        migrations.CreateModel(
            name='AirflowDagManage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dag_id', models.CharField(default='', max_length=100, verbose_name='DAG_ID')),
                ('dag_name', models.CharField(default='', max_length=100, verbose_name='DAG한글명')),
                ('service_name', models.CharField(default='', max_length=100, verbose_name='서비스명')),
                ('remarks', models.CharField(default='', max_length=100, verbose_name='비고')),
                ('team', models.CharField(default='', max_length=100, verbose_name='팀')),
                ('req_user', models.CharField(default='', max_length=100, verbose_name='요청자')),
            ],
            options={
                'verbose_name': 'Airflow 관리',
                'verbose_name_plural': 'Airflow 관리',
                'db_table': 'cust_airflow_manage',
            },
        ),
        migrations.AlterField(
            model_name='stddomain',
            name='group_code_yn',
            field=models.CharField(blank=True, choices=[('0', '그룹코드(공통코드테이블)'), ('1', '개별코드(별도테이블)')], max_length=30, null=True, verbose_name='코드유형'),
        ),
    ]
