# Generated by Django 3.0.6 on 2020-08-18 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0276_auto_20200818_0952'),
    ]

    operations = [
        migrations.AlterField(
            model_name='airflowdagmanage',
            name='remarks',
            field=models.CharField(blank=True, default='', max_length=100, null=True, verbose_name='비고'),
        ),
    ]
