# Generated by Django 3.0.6 on 2020-08-25 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0277_auto_20200818_0958'),
    ]

    operations = [
        migrations.AlterField(
            model_name='metareq',
            name='da_dev_comment',
            field=models.CharField(max_length=1000, null=True, verbose_name='DA개발승인의견'),
        ),
        migrations.AlterField(
            model_name='metareq',
            name='dba_dev_comment',
            field=models.CharField(max_length=1000, null=True, verbose_name='DBA개발승인의견'),
        ),
        migrations.AlterField(
            model_name='metareq',
            name='dba_prod_comment',
            field=models.CharField(max_length=1000, null=True, verbose_name='DBA운영승인의견'),
        ),
        migrations.AlterField(
            model_name='metareq',
            name='pl_dev_comment',
            field=models.CharField(max_length=1000, null=True, verbose_name='PL개발승인의견'),
        ),
        migrations.AlterField(
            model_name='metareq',
            name='pl_prod_comment',
            field=models.CharField(max_length=1000, null=True, verbose_name='PL운영승인의견'),
        ),
        migrations.AlterField(
            model_name='metareq',
            name='req_prod_comment',
            field=models.CharField(max_length=1000, null=True, verbose_name='운영반영요청의견'),
        ),
    ]
