# Generated by Django 3.0.6 on 2020-08-27 22:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0278_auto_20200825_1237'),
    ]

    operations = [
        migrations.AddField(
            model_name='dbowner',
            name='table_count',
            field=models.IntegerField(default=0, verbose_name='테이블개수'),
        ),
    ]
