# Generated by Django 3.0.6 on 2020-08-31 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0281_remove_dbtablespace_table_count'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='dbowner',
            options={'ordering': ('owner',), 'verbose_name': '메타관리 노출 OWNER', 'verbose_name_plural': '메타관리 노출 OWNER'},
        ),
        migrations.AlterModelOptions(
            name='dbtablespace',
            options={'verbose_name': '테이블스페이스 매핑 : OWNER<->TABLESPACE', 'verbose_name_plural': '테이블스페이스 매핑 : OWNER<->TABLESPACE'},
        ),
        migrations.AlterModelOptions(
            name='domain',
            options={'verbose_name': '업무도메인관리 (고객/상품/주문....)', 'verbose_name_plural': '업무도메인관리 (고객/상품/주문....)'},
        ),
        migrations.AlterModelOptions(
            name='domainanddblist',
            options={'verbose_name': '테이블 도메인<->데이터베이스 매핑', 'verbose_name_plural': '테이블 도메인<->데이터베이스 매핑'},
        ),
        migrations.AlterModelOptions(
            name='metagrantdetail',
            options={'verbose_name': '테이블 권한 : API(서비스)<->권한 매핑', 'verbose_name_plural': '테이블 권한 : API(서비스)<->권한 매핑'},
        ),
        migrations.AlterModelOptions(
            name='metagrantlist',
            options={'ordering': ('app_service',), 'verbose_name': '테이블 권한 : DB<->API(서비스) 매핑', 'verbose_name_plural': '테이블 권한 : DB<->API(서비스) 매핑'},
        ),
        migrations.AlterModelOptions(
            name='metareq',
            options={'verbose_name': '메타관리(테이블변경신청)', 'verbose_name_plural': '메타관리(테이블변경신청)'},
        ),
        migrations.AlterModelOptions(
            name='sendemailtargetlist',
            options={'verbose_name': 'DB정기반영 DEFAULT 이메일수신자', 'verbose_name_plural': 'DB정기반영 DEFAULT 이메일수신자'},
        ),
        migrations.AlterModelOptions(
            name='tablelist',
            options={'verbose_name': 'Table 관리', 'verbose_name_plural': 'Table 관리'},
        ),
        migrations.AddField(
            model_name='monitoritemlist',
            name='exp_order',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='노출순서'),
        ),
    ]
