# Generated by Django 3.0.6 on 2020-09-10 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0283_auto_20200910_1230'),
    ]

    operations = [
        migrations.AddField(
            model_name='stdattr',
            name='mod_dtm',
            field=models.DateTimeField(auto_now=True, null=True, verbose_name='수정일자'),
        ),
    ]
