# Generated by Django 3.0.6 on 2020-09-16 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0285_auto_20200916_1423'),
    ]

    operations = [
        migrations.AddField(
            model_name='datamodel',
            name='title',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='도메인'),
        ),
        migrations.AlterField(
            model_name='datamodel',
            name='file',
            field=models.FileField(null=True, upload_to='', verbose_name='모델업로드'),
        ),
    ]
