# Generated by Django 3.0.6 on 2020-09-16 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0286_auto_20200916_1444'),
    ]

    operations = [
        migrations.AddField(
            model_name='datamodel',
            name='exp_order',
            field=models.IntegerField(blank=True, default=99, null=True, verbose_name='화면노출순서'),
        ),
    ]
