# Generated by Django 3.0.6 on 2020-11-18 09:57

import database.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0291_menulist_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='datamodel',
            name='id_domainanddblist',
            field=models.ForeignKey(blank=True, db_column='id_domainanddblist', null=True, on_delete=django.db.models.deletion.SET_NULL, to='database.DomainAndDbList', verbose_name='도메인명'),
        ),
        migrations.AlterField(
            model_name='datamodel',
            name='exp_order',
            field=models.IntegerField(blank=True, default=99, help_text='같은 DB 내 도메인 노출 순서', null=True, verbose_name='화면노출순서'),
        ),
        migrations.AlterField(
            model_name='datamodel',
            name='file',
            field=models.FileField(null=True, upload_to='', validators=[database.models.validate_file_extension], verbose_name='모델업로드'),
        ),
        migrations.AlterField(
            model_name='datamodel',
            name='title',
            field=models.CharField(blank=True, help_text='상세 도메인이 없는 경우 DB용도와 동일 값 입력', max_length=200, null=True, verbose_name='도메인'),
        ),
    ]
