# Generated by Django 3.0.6 on 2020-11-23 11:03

import database.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('database', '0293_auto_20201119_0942'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='dbdetailmonitoritemlist',
            options={'verbose_name': 'DB서버 별 모니터링 상세', 'verbose_name_plural': 'DB서버 별 모니터링 상세'},
        ),
        migrations.AlterField(
            model_name='datamodel',
            name='file',
            field=models.FileField(help_text='반드시 물리 모델 업로드, 논리 모델은 안됨', null=True, upload_to='', validators=[database.models.validate_file_extension], verbose_name='모델업로드'),
        ),
        migrations.AlterField(
            model_name='dbdetailmonitoritemlist',
            name='compare_case',
            field=models.CharField(blank=True, choices=[('0', '='), ('1', '<'), ('2', '>')], default='0', max_length=30, null=True, verbose_name='정상조건(오른쪽 임계치 보다 < 작으면 정상'),
        ),
        migrations.AlterField(
            model_name='dbdetailmonitoritemlist',
            name='risk_level',
            field=models.CharField(blank=True, choices=[('0', '주의'), ('1', '심각'), ('2', '장애')], default='0', max_length=30, null=True, verbose_name='리스크레벨'),
        ),
        migrations.AlterField(
            model_name='domainanddblist',
            name='erd_user',
            field=models.CharField(blank=True, default='', help_text='ex: ORD_ERD, PRD_ERD', max_length=100, null=True, verbose_name='ERD계정명'),
        ),
        migrations.CreateModel(
            name='MonitorManagement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('monitor_name', models.CharField(blank=True, max_length=100, null=True, verbose_name='모니터링명')),
                ('monitor_cd', models.CharField(blank=True, max_length=100, null=True, verbose_name='모니터링코드')),
                ('reg_dtm', models.DateTimeField(auto_now_add=True, null=True, verbose_name='등록일자')),
                ('mod_dtm', models.DateTimeField(auto_now=True, null=True, verbose_name='수정일자')),
                ('id_dbdetail', models.ManyToManyField(blank=True, db_table='cust_monitorm_dbdetail', help_text='모니터링이 필요한 DB를 선택하세요', related_name='cust_monitorm_dbdetail', to='database.DbDetail', verbose_name='모니터링DB선택')),
                ('id_mod_user', models.ForeignKey(blank=True, db_column='id_mod_user', null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='수정자')),
            ],
            options={
                'verbose_name': '모니터링관리',
                'verbose_name_plural': '테이블스페이스 모니터링, 임계치 조정',
                'db_table': 'cust_monitor_management',
            },
        ),
    ]
