# Generated by Django 3.0.6 on 2020-11-23 11:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0294_auto_20201123_1103'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='monitormanagement',
            options={'verbose_name': '모니터링관리', 'verbose_name_plural': '모니터링관리'},
        ),
        migrations.RemoveField(
            model_name='monitormanagement',
            name='monitor_cd',
        ),
    ]
