# Generated by Django 3.0.6 on 2020-11-23 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0295_auto_20201123_1146'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MonitorManage',
        ),
        migrations.AddField(
            model_name='monitormanagement',
            name='alert_yn',
            field=models.CharField(choices=[('1', 'Y'), ('0', 'N')], default='0', max_length=30, verbose_name='전체 Alert 여부'),
        ),
        migrations.AddField(
            model_name='monitormanagement',
            name='monitor_yn',
            field=models.CharField(choices=[('1', 'Y'), ('0', 'N')], default='0', max_length=30, verbose_name='전체 모니터링 여부'),
        ),
        migrations.AlterField(
            model_name='monitormanagement',
            name='id_dbdetail',
            field=models.ManyToManyField(blank=True, db_table='cust_monitorm_dbdetail', help_text='모니터링이 필요한 DB를 선택하세요', limit_choices_to=models.Q(('id_hacase__in', [1, 2]), ('oper_cd__in', [3, 4])), related_name='cust_monitorm_dbdetail', to='database.DbDetail', verbose_name='모니터링DB선택'),
        ),
    ]
