# Generated by Django 3.0.6 on 2020-11-24 12:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0296_auto_20201123_1354'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dbdetail',
            name='monitor_yn',
        ),
    ]
