# Generated by Django 3.0.6 on 2020-11-24 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0297_remove_dbdetail_monitor_yn'),
    ]

    operations = [
        migrations.AddField(
            model_name='dbdetail',
            name='sync_db_edition',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='에디션'),
        ),
        migrations.AddField(
            model_name='dbdetail',
            name='sync_db_eos',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='DB EOS'),
        ),
        migrations.AddField(
            model_name='dbdetail',
            name='sync_db_nm',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='DB명'),
        ),
        migrations.AddField(
            model_name='dbdetail',
            name='sync_db_port',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='포트'),
        ),
        migrations.AddField(
            model_name='dbdetail',
            name='sync_db_pos',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='DBMS 위치'),
        ),
        migrations.AddField(
            model_name='dbdetail',
            name='sync_db_type',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='DB타입'),
        ),
        migrations.AddField(
            model_name='dbdetail',
            name='sync_db_version',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='버전'),
        ),
        migrations.AddField(
            model_name='dbdetail',
            name='sync_hostnm',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='호스트명'),
        ),
        migrations.AddField(
            model_name='dbdetail',
            name='sync_license_charge_yn',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='라이선스 과금유무'),
        ),
        migrations.AddField(
            model_name='dbdetail',
            name='sync_license_std',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='라이선스정책 (Oracle)'),
        ),
        migrations.AddField(
            model_name='dbdetail',
            name='sync_license_use',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='라이선스 정책적용'),
        ),
        migrations.AddField(
            model_name='dbdetail',
            name='sync_os_cpu_performance',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='CPU 성능'),
        ),
        migrations.AddField(
            model_name='dbdetail',
            name='sync_os_cpu_socket',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='CPU 소켓수'),
        ),
        migrations.AddField(
            model_name='dbdetail',
            name='sync_os_cpu_socket_core',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='소켓당 코어수'),
        ),
        migrations.AddField(
            model_name='dbdetail',
            name='sync_os_cpu_total_core',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='전체 코어수'),
        ),
        migrations.AddField(
            model_name='dbdetail',
            name='sync_os_cpu_type',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='CPU타입'),
        ),
        migrations.AddField(
            model_name='dbdetail',
            name='sync_os_memory',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='메모리'),
        ),
        migrations.AddField(
            model_name='dbdetail',
            name='sync_os_patch',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='OS패치'),
        ),
        migrations.AddField(
            model_name='dbdetail',
            name='sync_os_real_use_core',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='실사용 코어수'),
        ),
        migrations.AddField(
            model_name='dbdetail',
            name='sync_os_real_use_thread',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='실사용 쓰레드수'),
        ),
        migrations.AddField(
            model_name='dbdetail',
            name='sync_os_server_active',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='서버 활성화'),
        ),
        migrations.AddField(
            model_name='dbdetail',
            name='sync_os_thread_factor',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='쓰레드 팩터'),
        ),
        migrations.AddField(
            model_name='dbdetail',
            name='sync_os_version',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='OS버전'),
        ),
        migrations.AddField(
            model_name='dbdetail',
            name='sync_server_manage',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='서버 관리'),
        ),
        migrations.AddField(
            model_name='dbdetail',
            name='sync_srv_ip',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='서버IP'),
        ),
        migrations.AddField(
            model_name='dbdetail',
            name='sync_svc_ip',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='서비스IP'),
        ),
        migrations.AlterField(
            model_name='dbdetail',
            name='alert_yn',
            field=models.CharField(blank=True, choices=[('1', 'Y'), ('0', 'N')], default='1', help_text='Alert 여부. N 일 경우 Alert 만 비활성화', max_length=30, null=True, verbose_name='Alert여부'),
        ),
    ]
