# Generated by Django 3.0.6 on 2020-11-24 21:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0299_dbdetail_id_dbposition'),
    ]

    operations = [
        migrations.AddField(
            model_name='dbdetail',
            name='sync_db_order',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='DB별순서'),
        ),
        migrations.AddField(
            model_name='dbdetail',
            name='sync_hacase',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='HA구분'),
        ),
        migrations.AddField(
            model_name='dbdetail',
            name='sync_oper_cd',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='운영 구분'),
        ),
        migrations.AlterField(
            model_name='dbdetail',
            name='sync_db_pos',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='DBMS위치'),
        ),
    ]
