# Generated by Django 3.0.6 on 2020-11-26 09:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0300_auto_20201124_2115'),
    ]

    operations = [
        migrations.AddField(
            model_name='monitoritemlist',
            name='id_hacase',
            field=models.ForeignKey(blank=True, db_column='id_hacase', null=True, on_delete=django.db.models.deletion.PROTECT, to='database.HaCase', verbose_name='HA구분'),
        ),
        migrations.AlterField(
            model_name='dbdetail',
            name='sync_db_edition',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='(sync) 에디션'),
        ),
        migrations.AlterField(
            model_name='dbdetail',
            name='sync_db_eos',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='(sync) DB EOS'),
        ),
        migrations.AlterField(
            model_name='dbdetail',
            name='sync_db_nm',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='(sync) DB명'),
        ),
        migrations.AlterField(
            model_name='dbdetail',
            name='sync_db_order',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='(sync) DB별순서'),
        ),
        migrations.AlterField(
            model_name='dbdetail',
            name='sync_db_port',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='(sync) 포트'),
        ),
        migrations.AlterField(
            model_name='dbdetail',
            name='sync_db_pos',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='(sync) DBMS위치'),
        ),
        migrations.AlterField(
            model_name='dbdetail',
            name='sync_db_type',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='(sync) DB타입'),
        ),
        migrations.AlterField(
            model_name='dbdetail',
            name='sync_db_version',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='(sync) 버전'),
        ),
        migrations.AlterField(
            model_name='dbdetail',
            name='sync_hacase',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='(sync) HA구분'),
        ),
        migrations.AlterField(
            model_name='dbdetail',
            name='sync_hostnm',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='(sync) 호스트명'),
        ),
        migrations.AlterField(
            model_name='dbdetail',
            name='sync_license_charge_yn',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='(sync) 라이선스 과금유무'),
        ),
        migrations.AlterField(
            model_name='dbdetail',
            name='sync_license_std',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='(sync) 라이선스정책 (Oracle)'),
        ),
        migrations.AlterField(
            model_name='dbdetail',
            name='sync_license_use',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='(sync) 라이선스 정책적용'),
        ),
        migrations.AlterField(
            model_name='dbdetail',
            name='sync_oper_cd',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='(sync) 운영 구분'),
        ),
        migrations.AlterField(
            model_name='dbdetail',
            name='sync_os_cpu_performance',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='(sync) CPU 성능'),
        ),
        migrations.AlterField(
            model_name='dbdetail',
            name='sync_os_cpu_socket',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='(sync) CPU 소켓수'),
        ),
        migrations.AlterField(
            model_name='dbdetail',
            name='sync_os_cpu_socket_core',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='(sync) 소켓당 코어수'),
        ),
        migrations.AlterField(
            model_name='dbdetail',
            name='sync_os_cpu_total_core',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='(sync) 전체 코어수'),
        ),
        migrations.AlterField(
            model_name='dbdetail',
            name='sync_os_cpu_type',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='(sync) CPU타입'),
        ),
        migrations.AlterField(
            model_name='dbdetail',
            name='sync_os_memory',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='(sync) 메모리'),
        ),
        migrations.AlterField(
            model_name='dbdetail',
            name='sync_os_patch',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='(sync) OS패치'),
        ),
        migrations.AlterField(
            model_name='dbdetail',
            name='sync_os_real_use_core',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='(sync) 실사용 코어수'),
        ),
        migrations.AlterField(
            model_name='dbdetail',
            name='sync_os_real_use_thread',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='(sync) 실사용 쓰레드수'),
        ),
        migrations.AlterField(
            model_name='dbdetail',
            name='sync_os_server_active',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='(sync) 서버 활성화'),
        ),
        migrations.AlterField(
            model_name='dbdetail',
            name='sync_os_thread_factor',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='(sync) 쓰레드 팩터'),
        ),
        migrations.AlterField(
            model_name='dbdetail',
            name='sync_os_version',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='(sync) OS버전'),
        ),
        migrations.AlterField(
            model_name='dbdetail',
            name='sync_server_manage',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='(sync) 서버 관리'),
        ),
        migrations.AlterField(
            model_name='dbdetail',
            name='sync_srv_ip',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='(sync) 서버IP'),
        ),
        migrations.AlterField(
            model_name='dbdetail',
            name='sync_svc_ip',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='(sync) 서비스IP'),
        ),
    ]
