# Generated by Django 3.0.6 on 2020-11-26 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0301_auto_20201126_0918'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='dbdetailmonitoritemlist',
            options={'verbose_name': '모니터링 항목 등록 - 한 개 이상 등록 시 모니터링 활성화 ( Health Check 일 경우 임계치는 OPEN 입력 )', 'verbose_name_plural': '모니터링 항목 등록 - 한 개 이상 등록 시 모니터링 활성화 ( Health Check 일 경우 임계치는 OPEN 입력 )'},
        ),
        migrations.AddField(
            model_name='dbtype',
            name='version',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='버전'),
        ),
    ]
