# Generated by Django 3.0.6 on 2020-11-26 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0302_auto_20201126_1122'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dbtype',
            name='version',
            field=models.IntegerField(blank=True, help_text='숫자,소수점', null=True, verbose_name='버전'),
        ),
    ]
