# Generated by Django 3.0.6 on 2020-11-26 12:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0303_auto_20201126_1208'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='dbdetailmonitoritemlist',
            options={'verbose_name': 'DB서버 별 모니터링 상세', 'verbose_name_plural': 'DB서버 별 모니터링 상세'},
        ),
        migrations.AlterField(
            model_name='dbdetail',
            name='db_nm',
            field=models.CharField(help_text='MySQL 일 경우 show database 명 입력', max_length=100, verbose_name='DB명'),
        ),
        migrations.AlterField(
            model_name='dbdetail',
            name='id_dblist',
            field=models.ForeignKey(db_column='id_dblist', null=True, on_delete=django.db.models.deletion.CASCADE, to='database.DbList', verbose_name='DB용도'),
        ),
        migrations.AlterField(
            model_name='dbdetail',
            name='id_hacase',
            field=models.ForeignKey(db_column='id_hacase', null=True, on_delete=django.db.models.deletion.PROTECT, to='database.HaCase', verbose_name='HA구분'),
        ),
        migrations.AlterField(
            model_name='dbdetail',
            name='inst_nm',
            field=models.CharField(help_text='MySQL 일 경우 show database 명 입력', max_length=100, verbose_name='인스턴스명'),
        ),
        migrations.AlterField(
            model_name='dbdetail',
            name='oper_cd',
            field=models.ForeignKey(db_column='oper_cd', null=True, on_delete=django.db.models.deletion.PROTECT, to='database.OperCd', verbose_name='운영구분'),
        ),
        migrations.AlterField(
            model_name='dbtype',
            name='version',
            field=models.FloatField(blank=True, help_text='숫자,소수점', null=True, verbose_name='버전'),
        ),
    ]
