# Generated by Django 3.0.6 on 2020-11-30 10:49

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('database', '0304_auto_20201126_1257'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='monitoritemlist',
            options={'ordering': ['id_dbtype', 'exp_order'], 'verbose_name': '모니터링 Item 상세', 'verbose_name_plural': '모니터링 Item 상세'},
        ),
        migrations.RemoveField(
            model_name='monitoritemlist',
            name='lv2_item_nm',
        ),
        migrations.AlterField(
            model_name='monitoritemlist',
            name='item_nm',
            field=models.CharField(max_length=100, verbose_name='모니터링 항목'),
        ),
        migrations.CreateModel(
            name='MonitorItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_nm', models.CharField(default='', help_text='"parameter 명 사용되며 알파벳+언더바만 사용 가능', max_length=100, validators=[django.core.validators.RegexValidator('^[a-zA-Z_]*$', '영문,언더바(_)만 입력 가능합니다.')], verbose_name='모니터링 항목')),
                ('monitor_level', models.CharField(choices=[('0', 'SQL'), ('1', 'OS')], default='0', max_length=30, verbose_name='모니터링Level')),
                ('mod_dtm', models.DateTimeField(auto_now=True, null=True, verbose_name='수정일자')),
                ('id_reg_user', models.ForeignKey(blank=True, db_column='id_reg_user', null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='등록자')),
            ],
            options={
                'verbose_name': '모니터링 Item 마스터',
                'verbose_name_plural': '모니터링 Item 마스터',
                'db_table': 'cust_monitor_item',
            },
        ),
    ]
