# Generated by Django 3.0.6 on 2020-11-30 11:05

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0305_auto_20201130_1049'),
    ]

    operations = [
        migrations.AddField(
            model_name='monitoritemlist',
            name='id_monitoritem',
            field=models.ForeignKey(blank=True, db_column='id_monitoritem', null=True, on_delete=django.db.models.deletion.CASCADE, to='database.MonitorItem', verbose_name='모니터링ITEM명'),
        ),
        migrations.AlterField(
            model_name='monitoritem',
            name='item_nm',
            field=models.CharField(default='', help_text='"parameter 명 사용되며 알파벳+언더바만 사용 가능', max_length=100, validators=[django.core.validators.RegexValidator('^[a-zA-Z_ ]*$', '영문,언더바(_),스페이스만 입력 가능합니다.')], verbose_name='모니터링 항목'),
        ),
    ]
