# Generated by Django 3.0.6 on 2020-11-30 11:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0307_auto_20201130_1131'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='monitoritemlist',
            name='sms_message',
        ),
    ]
