# Generated by Django 3.0.6 on 2020-11-30 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0308_remove_monitoritemlist_sms_message'),
    ]

    operations = [
        migrations.AddField(
            model_name='dbdetailmonitoritemlist',
            name='note1',
            field=models.CharField(blank=True, max_length=300, null=True, verbose_name='노트1'),
        ),
        migrations.AlterField(
            model_name='dbdetailmonitoritemlist',
            name='compare_case',
            field=models.CharField(blank=True, choices=[('0', '='), ('1', '<'), ('2', '>')], default='0', max_length=30, null=True, verbose_name='(임계치) 보다 모니터링값이 (부등호) ..하면 (리스크레벨)'),
        ),
        migrations.AlterField(
            model_name='monitoritemlist',
            name='compare_case',
            field=models.CharField(choices=[('0', '='), ('1', '<'), ('2', '>')], default='0', max_length=30, verbose_name='(임계치) 보다 모니터링값이 (부등호) ..하면 (리스크레벨)'),
        ),
    ]
