# Generated by Django 3.0.6 on 2020-11-30 15:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0309_auto_20201130_1454'),
    ]

    operations = [
        migrations.AddField(
            model_name='monitoritemlog',
            name='id_dbdetailmonitoritemlist',
            field=models.ForeignKey(blank=True, db_column='id_dbdetailmonitoritemlist', null=True, on_delete=django.db.models.deletion.CASCADE, to='database.DBDetailMonitorItemList', verbose_name='모니터링타겟'),
        ),
    ]
