# Generated by Django 3.0.6 on 2020-12-01 13:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0311_osuser'),
    ]

    operations = [
        migrations.DeleteModel(
            name='OsUser',
        ),
    ]
