# Generated by Django 3.0.6 on 2020-12-01 17:19

from django.db import migrations
import django_safe_fields.fields


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0314_osuser_passwd'),
    ]

    operations = [
        migrations.AddField(
            model_name='osuser',
            name='passwd2',
            field=django_safe_fields.fields.SafeCharField(blank=True, max_length=128, null=True, verbose_name='비밀번호2'),
        ),
    ]
