# Generated by Django 3.0.6 on 2020-12-01 20:17

from django.db import migrations
import django_safe_fields.fields


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0316_auto_20201201_1823'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='osuser',
            name='passwd',
        ),
        migrations.RemoveField(
            model_name='osuser',
            name='passwd2',
        ),
        migrations.RemoveField(
            model_name='osuser',
            name='password3',
        ),
        migrations.AlterField(
            model_name='osuser',
            name='password',
            field=django_safe_fields.fields.SafeCharField(default='', max_length=128, verbose_name='패스워드'),
        ),
    ]
