# Generated by Django 3.0.6 on 2020-12-03 10:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('database', '0317_auto_20201201_2017'),
    ]

    operations = [
        migrations.CreateModel(
            name='Db',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('db_type', models.CharField(blank=True, max_length=100, null=True, verbose_name='DBMS종류')),
                ('reg_dtm', models.DateTimeField(auto_now_add=True, null=True, verbose_name='등록일자')),
                ('id_reg_user', models.ForeignKey(blank=True, db_column='id_reg_user', null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='등록자')),
            ],
            options={
                'verbose_name': 'DBMS 종류',
                'verbose_name_plural': 'DBMS 종류',
                'db_table': 'cust_db',
            },
        ),
        migrations.AddField(
            model_name='dbtype',
            name='id_db',
            field=models.ForeignKey(blank=True, db_column='id_db', null=True, on_delete=django.db.models.deletion.PROTECT, to='database.Db', verbose_name='DBMS위치'),
        ),
    ]
