# Generated by Django 3.0.6 on 2020-12-03 10:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0318_auto_20201203_1033'),
    ]

    operations = [
        migrations.RenameField(
            model_name='db',
            old_name='id_reg_user',
            new_name='id_mod_user',
        ),
        migrations.RenameField(
            model_name='db',
            old_name='reg_dtm',
            new_name='mod_dtm',
        ),
    ]
