# Generated by Django 3.0.6 on 2020-12-03 13:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_safe_fields.fields


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('database', '0319_auto_20201203_1035'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='db',
            options={'verbose_name': '사용하는 DBMS', 'verbose_name_plural': '사용하는 DBMS'},
        ),
        migrations.AlterModelOptions(
            name='dbtype',
            options={'verbose_name': '사용하는 DBMS 버전', 'verbose_name_plural': '사용하는 DBMS 버전'},
        ),
        migrations.AlterModelOptions(
            name='domainanddblist',
            options={'verbose_name': '업무도메인/담당자(테이블담당자) 매핑', 'verbose_name_plural': '업무도메인/담당자(테이블담당자) 매핑'},
        ),
        migrations.CreateModel(
            name='DbUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(blank=True, max_length=100, null=True, verbose_name='DB계정명')),
                ('password', django_safe_fields.fields.SafeCharField(default='', max_length=128, verbose_name='패스워드')),
                ('req_reason', models.CharField(blank=True, max_length=1000, null=True, verbose_name='생성목적')),
                ('use_yn', models.CharField(blank=True, choices=[('1', 'Y'), ('0', 'N')], default='1', max_length=30, null=True, verbose_name='사용여부')),
                ('mod_dtm', models.DateTimeField(auto_now=True, null=True, verbose_name='수정일자')),
                ('id_dblist', models.ForeignKey(db_column='id_dblist', on_delete=django.db.models.deletion.PROTECT, to='database.DbList', verbose_name='DB')),
                ('id_mod_user', models.ForeignKey(blank=True, db_column='id_mod_user', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='DbUser_id_mod_user', to=settings.AUTH_USER_MODEL, verbose_name='수정자')),
                ('id_req_user', models.ForeignKey(blank=True, db_column='id_req_user', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='DbUser_id_req_user', to=settings.AUTH_USER_MODEL, verbose_name='요청자')),
            ],
            options={
                'verbose_name': 'DB계정정보',
                'verbose_name_plural': 'DB계정정보',
                'db_table': 'cust_db_user',
            },
        ),
    ]
