# Generated by Django 3.0.6 on 2020-12-03 13:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0320_auto_20201203_1336'),
    ]

    operations = [
        migrations.AddField(
            model_name='dbuser',
            name='oper_cd',
            field=models.ForeignKey(blank=True, db_column='oper_cd', null=True, on_delete=django.db.models.deletion.PROTECT, to='database.OperCd', verbose_name='운영구분'),
        ),
    ]
