# Generated by Django 3.0.6 on 2020-12-03 13:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('database', '0321_dbuser_oper_cd'),
    ]

    operations = [
        migrations.AddField(
            model_name='dbuser',
            name='id_reg_user',
            field=models.ForeignKey(blank=True, db_column='id_reg_user', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='DbUser_id_reg_user', to=settings.AUTH_USER_MODEL, verbose_name='등록자'),
        ),
        migrations.AddField(
            model_name='dbuser',
            name='reg_dtm',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='등록일자'),
        ),
        migrations.AlterField(
            model_name='dbuser',
            name='id_req_user',
            field=models.ForeignKey(db_column='id_req_user', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='DbUser_id_req_user', to=settings.AUTH_USER_MODEL, verbose_name='요청자'),
        ),
        migrations.AlterField(
            model_name='dbuser',
            name='oper_cd',
            field=models.ForeignKey(db_column='oper_cd', null=True, on_delete=django.db.models.deletion.PROTECT, to='database.OperCd', verbose_name='운영구분'),
        ),
        migrations.AlterField(
            model_name='dbuser',
            name='req_reason',
            field=models.TextField(max_length=1000, null=True, verbose_name='생성목적'),
        ),
        migrations.AlterField(
            model_name='dbuser',
            name='use_yn',
            field=models.CharField(choices=[('1', 'Y'), ('0', 'N')], default='1', max_length=30, null=True, verbose_name='사용여부'),
        ),
        migrations.AlterField(
            model_name='dbuser',
            name='username',
            field=models.CharField(max_length=100, null=True, verbose_name='DB계정명'),
        ),
    ]
