# Generated by Django 3.0.6 on 2020-12-03 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0322_auto_20201203_1348'),
    ]

    operations = [
        migrations.AddField(
            model_name='dbuser',
            name='conn_ip',
            field=models.CharField(blank=True, help_text='Mysql, Mariadb일 경우 입력', max_length=100, null=True, verbose_name='접속IP'),
        ),
    ]
