# Generated by Django 3.0.6 on 2020-12-03 15:11

from django.db import migrations, models
import django_safe_fields.fields


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0323_dbuser_conn_ip'),
    ]

    operations = [
        migrations.AddField(
            model_name='userlist',
            name='conn_ip',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='접속IP'),
        ),
        migrations.AlterField(
            model_name='dbuser',
            name='password',
            field=django_safe_fields.fields.SafeCharField(default='', help_text='* 개발 : dev#DB계정명(알파벳만)!@34<br>* 운영 : gs#DB계정명(알파벤만)!@34', max_length=128, verbose_name='패스워드'),
        ),
    ]
