# Generated by Django 3.0.6 on 2020-12-04 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0325_auto_20201204_0946'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='dbuser',
            options={'verbose_name': 'DB (서비스)계정정보', 'verbose_name_plural': 'DB (서비스)계정정보'},
        ),
        migrations.AddField(
            model_name='dblist',
            name='disposal_desc',
            field=models.TextField(blank=True, max_length=4000, null=True, verbose_name='폐기노트'),
        ),
        migrations.AddField(
            model_name='dblist',
            name='disposal_dt',
            field=models.DateField(blank=True, null=True, verbose_name='폐기일자'),
        ),
    ]
