# Generated by Django 3.0.6 on 2020-12-04 23:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0326_auto_20201204_1129'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='monitoritemlog',
            name='id_dbdetail',
        ),
        migrations.RemoveField(
            model_name='monitoritemlog',
            name='id_dblist',
        ),
        migrations.RemoveField(
            model_name='monitoritemlog',
            name='id_dbtype',
        ),
        migrations.RemoveField(
            model_name='monitoritemlog',
            name='id_monitoritemlist',
        ),
        migrations.RemoveField(
            model_name='monitoritemlog',
            name='id_opercd',
        ),
    ]
