# Generated by Django 3.0.6 on 2020-12-05 00:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0327_auto_20201204_2314'),
    ]

    operations = [
        migrations.AddField(
            model_name='monitoritemlist',
            name='linux_cmd',
            field=models.TextField(blank=True, help_text='"숫자만 리턴되도록 Script 입력', null=True, verbose_name='Linux 명령어'),
        ),
        migrations.AddField(
            model_name='monitoritemlist',
            name='unix_cmd',
            field=models.TextField(blank=True, help_text='"숫자만 리턴되도록 Script 입력', null=True, verbose_name='Unix 명령어'),
        ),
        migrations.AlterField(
            model_name='monitoritemlist',
            name='id_dbtype',
            field=models.ForeignKey(blank=True, db_column='id_dbtype', help_text='SQL 모니터링 시 버전 Dependency 가 있는 경우만 상세 버전 선택, 나머지는 버전 미표기 선택', null=True, on_delete=django.db.models.deletion.CASCADE, to='database.DbType', verbose_name='DBMS종류'),
        ),
        migrations.AlterField(
            model_name='monitoritemlist',
            name='id_hacase',
            field=models.ForeignKey(blank=True, db_column='id_hacase', help_text='MySQL Slave만 Seconday 선택, 나머지는 모두 Primary 선택', null=True, on_delete=django.db.models.deletion.PROTECT, to='database.HaCase', verbose_name='HA구분'),
        ),
        migrations.AlterField(
            model_name='monitoritemlist',
            name='sql_text',
            field=models.TextField(blank=True, help_text='"SELECT 절에는 단일 항목, 하나의 ROW만 조회되도록 작성', null=True, verbose_name='모니터링 SQL'),
        ),
    ]
