# Generated by Django 3.0.6 on 2020-12-05 20:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0328_auto_20201205_0008'),
    ]

    operations = [
        migrations.AlterField(
            model_name='monitoritemlist',
            name='column_name',
            field=models.CharField(blank=True, help_text='"SELECT 되는 컬럼 Alias', max_length=30, null=True, verbose_name='SQL내 모니터링 컬럼'),
        ),
        migrations.AlterField(
            model_name='monitoritemlist',
            name='compare_case',
            field=models.CharField(blank=True, choices=[('0', '='), ('1', '<'), ('2', '>')], max_length=30, null=True, verbose_name='(임계치) 보다 모니터링값이 (부등호) ..하면 (리스크레벨)'),
        ),
        migrations.AlterField(
            model_name='monitoritemlist',
            name='exp_order',
            field=models.IntegerField(blank=True, default=99, null=True, verbose_name='노출순서'),
        ),
        migrations.AlterField(
            model_name='monitoritemlist',
            name='limit_value',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Default임계치'),
        ),
        migrations.AlterField(
            model_name='monitoritemlist',
            name='risk_level',
            field=models.CharField(blank=True, choices=[('0', '주의'), ('1', '심각'), ('2', '장애')], max_length=30, null=True, verbose_name='Default 리스크레벨'),
        ),
    ]
