# Generated by Django 3.0.6 on 2020-12-07 09:07

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0330_monitoritemlist_relative_case'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='monitoritemlist',
            options={'ordering': ['id_dbtype'], 'verbose_name': '모니터링 Item 상세', 'verbose_name_plural': '모니터링 Item 상세'},
        ),
        migrations.RemoveField(
            model_name='monitoritemlist',
            name='exp_order',
        ),
        migrations.AlterField(
            model_name='monitoritem',
            name='item_nm',
            field=models.CharField(default='', help_text='"영문,언더바(_),스페이스만 입력 가능합니다.', max_length=100, validators=[django.core.validators.RegexValidator('^[a-zA-Z_/ ]*$', '영문,언더바(_),스페이스만 입력 가능합니다.')], verbose_name='모니터링 항목'),
        ),
    ]
