# Generated by Django 3.0.6 on 2020-12-10 23:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('database', '0332_monitoritem_exp_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='dbdetailmonitoritemlist',
            name='id_mod_user',
            field=models.ForeignKey(blank=True, db_column='id_mod_user', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='DBDetailMonitorItemList_mod_user', to=settings.AUTH_USER_MODEL, verbose_name='수정자'),
        ),
        migrations.AddField(
            model_name='dbdetailmonitoritemlist',
            name='mod_dtm',
            field=models.DateTimeField(auto_now=True, null=True, verbose_name='수정일자'),
        ),
        migrations.AlterField(
            model_name='dbdetailmonitoritemlist',
            name='id_reg_user',
            field=models.ForeignKey(blank=True, db_column='id_reg_user', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='DBDetailMonitorItemList_reg_user', to=settings.AUTH_USER_MODEL, verbose_name='등록자'),
        ),
        migrations.AlterField(
            model_name='dbuser',
            name='conn_ip',
            field=models.CharField(default='%', help_text='ORACLE : % 입력, Mysql Mariadb일 경우 접근하는 Source IP 입력', max_length=100, null=True, verbose_name='Source IP'),
        ),
        migrations.AlterField(
            model_name='monitoritem',
            name='item_nm',
            field=models.CharField(default='', max_length=100, verbose_name='모니터링 항목'),
        ),
    ]
