# Generated by Django 3.0.6 on 2021-06-08 21:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0333_auto_20201210_2313'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datalist',
            name='sql_text',
            field=models.TextField(blank=True, help_text='":"로 바인딩하여 SQL을 작성하면 동적으로 파라메터 값을 받을 수 있습니다. 예를들면, :상픔코드, :주문일자 와 같이 바인딩 사용 시 사용자가 SQL을 실행할 때 상품코드와 주문일자를 입력할 수 있습니다.<br><font color="red"><b>in (:in_param) 으로 사용 시 멀티 값 입력 가능합니다.</b></font>주의: :yyyy :mm :dd :hh :mi :ss :digit 등은 바인드 변수로 사용할 수 없습니다.', max_length=30000, null=True, verbose_name='관련SQL'),
        ),
        migrations.AlterField(
            model_name='monitormanagement',
            name='alert_yn',
            field=models.CharField(choices=[('1', 'ON'), ('0', 'OFF')], default='0', max_length=30, verbose_name='전체 Slack(Alert) 켜기/끄기 - DB작업 시 OFF'),
        ),
        migrations.AlterField(
            model_name='monitormanagement',
            name='monitor_yn',
            field=models.CharField(choices=[('1', 'ON'), ('0', 'OFF')], default='0', max_length=30, verbose_name='전체 모니터링 켜기/끄기'),
        ),
        migrations.AlterField(
            model_name='weekdba',
            name='dba',
            field=models.CharField(blank=True, choices=[('22980', '이치호'), ('22764', '이정아'), ('22917', '정관호'), ('D4563', '김진석')], max_length=30, null=True, verbose_name='DBA'),
        ),
    ]
